<?php

/**
 * eshop filter form base class.
 *
 * @package    deluxebuys
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseeshopFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'denominacion'                      => new sfWidgetFormFilterInput(),
      'dominio'                           => new sfWidgetFormFilterInput(),
      'id_marca'                          => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('marca'), 'add_empty' => true)),
      'id_producto_genero'                => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('productoGenero'), 'add_empty' => true)),
      'lookbook'                          => new sfWidgetFormFilterInput(),
      'lookbook_imagenes_fila'            => new sfWidgetFormFilterInput(),
      'usa_campaign'                      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'usa_menu_flotante'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'activo'                            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'facebook'                          => new sfWidgetFormFilterInput(),
      'twitter'                           => new sfWidgetFormFilterInput(),
      'instagram'                         => new sfWidgetFormFilterInput(),
      'youtube'                           => new sfWidgetFormFilterInput(),
      'snapchat'                          => new sfWidgetFormFilterInput(),
      'data_fiscal'                       => new sfWidgetFormFilterInput(),
      'usa_acerca'                        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'acerca_titulo'                     => new sfWidgetFormFilterInput(),
      'acerca_texto_principal'            => new sfWidgetFormFilterInput(),
      'acerca_texto_secundario'           => new sfWidgetFormFilterInput(),
      'tiendas_titulo'                    => new sfWidgetFormFilterInput(),
      'tiendas_subtitulo'                 => new sfWidgetFormFilterInput(),
      'mi_carro_titulo'                   => new sfWidgetFormFilterInput(),
      'mercado_pago_client_id'            => new sfWidgetFormFilterInput(),
      'mercado_pago_client_secret'        => new sfWidgetFormFilterInput(),
      'envio_pack_api_key'                => new sfWidgetFormFilterInput(),
      'envio_pack_secret_key'             => new sfWidgetFormFilterInput(),
      'envio_pack_direccion_envio'        => new sfWidgetFormFilterInput(),
      'razon_social'                      => new sfWidgetFormFilterInput(),
      'cuit'                              => new sfWidgetFormFilterInput(),
      'email_no_reply'                    => new sfWidgetFormFilterInput(),
      'ml_client_id'                      => new sfWidgetFormFilterInput(),
      'ml_client_secret'                  => new sfWidgetFormFilterInput(),
      'ml_id_usuario_interno'             => new sfWidgetFormFilterInput(),
      'ml_id_official_store'              => new sfWidgetFormFilterInput(),
      'link_color'                        => new sfWidgetFormFilterInput(),
      'lista_sendgrid'                    => new sfWidgetFormFilterInput(),
      'tags'                              => new sfWidgetFormFilterInput(),
      'soporte_email'                     => new sfWidgetFormFilterInput(),
      'soporte_pass'                      => new sfWidgetFormFilterInput(),
      'freeshipping'                      => new sfWidgetFormFilterInput(),
      'link_cace'                         => new sfWidgetFormFilterInput(),
      'devolucion_restringida_categorias' => new sfWidgetFormFilterInput(),
      'devolucion_restringida_mensaje'    => new sfWidgetFormFilterInput(),
      'devolucion_freeshipping'           => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'decidir_nro_comercio'              => new sfWidgetFormFilterInput(),
      'formulario_titulo'                 => new sfWidgetFormFilterInput(),
      'formulario_texto'                  => new sfWidgetFormFilterInput(),
      'formulario_campos'                 => new sfWidgetFormFilterInput(),
      'formulario_to'                     => new sfWidgetFormFilterInput(),
      'mail_RRHH'                         => new sfWidgetFormFilterInput(),
      'mail_comercial'                    => new sfWidgetFormFilterInput(),
      'lookbook_titulo'                   => new sfWidgetFormFilterInput(),
      'campaign_titulo'                   => new sfWidgetFormFilterInput(),
      'mails_OC'                          => new sfWidgetFormFilterInput(),
      'zendesk_config'                    => new sfWidgetFormFilterInput(),
      'texto_iniciar_sesion'              => new sfWidgetFormFilterInput(),
      'texto_seguinos'                    => new sfWidgetFormFilterInput(),
      'texto_agregar_al_carro'            => new sfWidgetFormFilterInput(),
      'texto_carro_de_compras'            => new sfWidgetFormFilterInput(),
      'texto_soy_miembro'                 => new sfWidgetFormFilterInput(),
      'texto_soy_nuevo'                   => new sfWidgetFormFilterInput(),
      'texto_consultas'                   => new sfWidgetFormFilterInput(),
      'domicilio_comercial'               => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'denominacion'                      => new sfValidatorPass(array('required' => false)),
      'dominio'                           => new sfValidatorPass(array('required' => false)),
      'id_marca'                          => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('marca'), 'column' => 'id_marca')),
      'id_producto_genero'                => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('productoGenero'), 'column' => 'id_producto_genero')),
      'lookbook'                          => new sfValidatorPass(array('required' => false)),
      'lookbook_imagenes_fila'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'usa_campaign'                      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'usa_menu_flotante'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'activo'                            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'facebook'                          => new sfValidatorPass(array('required' => false)),
      'twitter'                           => new sfValidatorPass(array('required' => false)),
      'instagram'                         => new sfValidatorPass(array('required' => false)),
      'youtube'                           => new sfValidatorPass(array('required' => false)),
      'snapchat'                          => new sfValidatorPass(array('required' => false)),
      'data_fiscal'                       => new sfValidatorPass(array('required' => false)),
      'usa_acerca'                        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'acerca_titulo'                     => new sfValidatorPass(array('required' => false)),
      'acerca_texto_principal'            => new sfValidatorPass(array('required' => false)),
      'acerca_texto_secundario'           => new sfValidatorPass(array('required' => false)),
      'tiendas_titulo'                    => new sfValidatorPass(array('required' => false)),
      'tiendas_subtitulo'                 => new sfValidatorPass(array('required' => false)),
      'mi_carro_titulo'                   => new sfValidatorPass(array('required' => false)),
      'mercado_pago_client_id'            => new sfValidatorPass(array('required' => false)),
      'mercado_pago_client_secret'        => new sfValidatorPass(array('required' => false)),
      'envio_pack_api_key'                => new sfValidatorPass(array('required' => false)),
      'envio_pack_secret_key'             => new sfValidatorPass(array('required' => false)),
      'envio_pack_direccion_envio'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'razon_social'                      => new sfValidatorPass(array('required' => false)),
      'cuit'                              => new sfValidatorPass(array('required' => false)),
      'email_no_reply'                    => new sfValidatorPass(array('required' => false)),
      'ml_client_id'                      => new sfValidatorPass(array('required' => false)),
      'ml_client_secret'                  => new sfValidatorPass(array('required' => false)),
      'ml_id_usuario_interno'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ml_id_official_store'              => new sfValidatorPass(array('required' => false)),
      'link_color'                        => new sfValidatorPass(array('required' => false)),
      'lista_sendgrid'                    => new sfValidatorPass(array('required' => false)),
      'tags'                              => new sfValidatorPass(array('required' => false)),
      'soporte_email'                     => new sfValidatorPass(array('required' => false)),
      'soporte_pass'                      => new sfValidatorPass(array('required' => false)),
      'freeshipping'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'link_cace'                         => new sfValidatorPass(array('required' => false)),
      'devolucion_restringida_categorias' => new sfValidatorPass(array('required' => false)),
      'devolucion_restringida_mensaje'    => new sfValidatorPass(array('required' => false)),
      'devolucion_freeshipping'           => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'decidir_nro_comercio'              => new sfValidatorPass(array('required' => false)),
      'formulario_titulo'                 => new sfValidatorPass(array('required' => false)),
      'formulario_texto'                  => new sfValidatorPass(array('required' => false)),
      'formulario_campos'                 => new sfValidatorPass(array('required' => false)),
      'formulario_to'                     => new sfValidatorPass(array('required' => false)),
      'mail_RRHH'                         => new sfValidatorPass(array('required' => false)),
      'mail_comercial'                    => new sfValidatorPass(array('required' => false)),
      'lookbook_titulo'                   => new sfValidatorPass(array('required' => false)),
      'campaign_titulo'                   => new sfValidatorPass(array('required' => false)),
      'mails_OC'                          => new sfValidatorPass(array('required' => false)),
      'zendesk_config'                    => new sfValidatorPass(array('required' => false)),
      'texto_iniciar_sesion'              => new sfValidatorPass(array('required' => false)),
      'texto_seguinos'                    => new sfValidatorPass(array('required' => false)),
      'texto_agregar_al_carro'            => new sfValidatorPass(array('required' => false)),
      'texto_carro_de_compras'            => new sfValidatorPass(array('required' => false)),
      'texto_soy_miembro'                 => new sfValidatorPass(array('required' => false)),
      'texto_soy_nuevo'                   => new sfValidatorPass(array('required' => false)),
      'texto_consultas'                   => new sfValidatorPass(array('required' => false)),
      'domicilio_comercial'               => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('eshop_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'eshop';
  }

  public function getFields()
  {
    return array(
      'id_eshop'                          => 'Number',
      'denominacion'                      => 'Text',
      'dominio'                           => 'Text',
      'id_marca'                          => 'ForeignKey',
      'id_producto_genero'                => 'ForeignKey',
      'lookbook'                          => 'Text',
      'lookbook_imagenes_fila'            => 'Number',
      'usa_campaign'                      => 'Boolean',
      'usa_menu_flotante'                 => 'Boolean',
      'activo'                            => 'Boolean',
      'facebook'                          => 'Text',
      'twitter'                           => 'Text',
      'instagram'                         => 'Text',
      'youtube'                           => 'Text',
      'snapchat'                          => 'Text',
      'data_fiscal'                       => 'Text',
      'usa_acerca'                        => 'Boolean',
      'acerca_titulo'                     => 'Text',
      'acerca_texto_principal'            => 'Text',
      'acerca_texto_secundario'           => 'Text',
      'tiendas_titulo'                    => 'Text',
      'tiendas_subtitulo'                 => 'Text',
      'mi_carro_titulo'                   => 'Text',
      'mercado_pago_client_id'            => 'Text',
      'mercado_pago_client_secret'        => 'Text',
      'envio_pack_api_key'                => 'Text',
      'envio_pack_secret_key'             => 'Text',
      'envio_pack_direccion_envio'        => 'Number',
      'razon_social'                      => 'Text',
      'cuit'                              => 'Text',
      'email_no_reply'                    => 'Text',
      'ml_client_id'                      => 'Text',
      'ml_client_secret'                  => 'Text',
      'ml_id_usuario_interno'             => 'Number',
      'ml_id_official_store'              => 'Text',
      'link_color'                        => 'Text',
      'lista_sendgrid'                    => 'Text',
      'tags'                              => 'Text',
      'soporte_email'                     => 'Text',
      'soporte_pass'                      => 'Text',
      'freeshipping'                      => 'Number',
      'link_cace'                         => 'Text',
      'devolucion_restringida_categorias' => 'Text',
      'devolucion_restringida_mensaje'    => 'Text',
      'devolucion_freeshipping'           => 'Boolean',
      'decidir_nro_comercio'              => 'Text',
      'formulario_titulo'                 => 'Text',
      'formulario_texto'                  => 'Text',
      'formulario_campos'                 => 'Text',
      'formulario_to'                     => 'Text',
      'mail_RRHH'                         => 'Text',
      'mail_comercial'                    => 'Text',
      'lookbook_titulo'                   => 'Text',
      'campaign_titulo'                   => 'Text',
      'mails_OC'                          => 'Text',
      'zendesk_config'                    => 'Text',
      'texto_iniciar_sesion'              => 'Text',
      'texto_seguinos'                    => 'Text',
      'texto_agregar_al_carro'            => 'Text',
      'texto_carro_de_compras'            => 'Text',
      'texto_soy_miembro'                 => 'Text',
      'texto_soy_nuevo'                   => 'Text',
      'texto_consultas'                   => 'Text',
      'domicilio_comercial'               => 'Text',
    );
  }
}
