<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version598 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->dropTable('movimiento_stock_oca_detalle');
		$this->dropTable('movimiento_stock_oca');
    }

    public function down()
    {

    }
}