<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version597 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('recepcion_mercaderia_campana', 'observacion', 'clob', '65535', array());
    }

    public function down()
    {

    }
}