<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version606 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('promo_pago', array(
             'id_promo_pago' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'denominacion' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'proveedor' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'id_forma_pago' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'vigencia_desde' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'vigencia_hasta' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'dias_semana' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'params' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'id_descuento' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'orden' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'activo' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_promo_pago',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('promo_pago');
    }
}