<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version603 extends Doctrine_Migration_Base
{
    public function up()
    {		
		$this->dropTable('devolucion_stock_programada');
    }

    public function down()
    {

    }
}