<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version618 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('campana', 'mostrar_banner_hover', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('campana', 'mostrar_banner_hover');
    }
}