<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version623 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('eshop_home_multimedia', array(
             'id_eshop_home_multimedia' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'src' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_eshop_home_multimedia',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('eshop_home_multimedia');
    }
}