<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version639 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop_imagen_campaign', 'activo', 'boolean', '25', array(
             ));
        $this->addColumn('eshop_lookbook', 'activo', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop_imagen_campaign', 'activo');
        $this->removeColumn('eshop_lookbook', 'activo');
    }
}