<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version634 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('eshop_imagen_campaign', array(
             'id_eshop_imagen_campaign' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_eshop_home' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_eshop_imagen_campaign',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('eshop_imagen_campaign:');
    }
}