<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version655 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('eshop_lookbook_producto', 'background_color', 'string', '255', array(
             ));
    }

    public function down()
    {

    }
}