<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version656 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'usa_menu_flotante', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'usa_menu_flotante');
    }
}