<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version660 extends Doctrine_Migration_Base
{
    public function up()
    {

        // Kimeika
        $eshop = eshopTable::getInstance()->findOneByIdEshop(6);
        $eshop->setOcaOperativaInversa('258825');
        $eshop->save();

 
        // SalSiPuedes
        $eshop = eshopTable::getInstance()->findOneByIdEshop(8);
        $eshop->setOcaNroCuenta('153499/000');
        $eshop->save();



        // Felix
        $eshop = eshopTable::getInstance()->findOneByIdEshop(9);

        $eshop->setOcaOperativaDOMEmpresa('255250');
        $eshop->setOcaOperativaOCAEmpresa('255252');
        $eshop->setOcaOperativaDOMCliente('255251');
        $eshop->setOcaOperativaOCACliente('255253');
        $eshop->setOcaOperativaInversa('259161');

        $eshop->save();




    }

    public function down()
    {

    }
}