
<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version665 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE producto_item SET stock_refuerzo = 0;");
    }

    public function down()
    {

    }
}