<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version676 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'link_cace', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'link_cace');
    }
}