<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version675 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('eshop', 'freeshipping', 'integer', '4', array(
             ));
    }

    public function down()
    {

    }
}