<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version669 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('stock', 'id_pedido_producto_item', 'integer', '4', array(
             'notnull' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('stock', 'id_pedido_producto_item');
    }
}