<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version677 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'tags_suscripcion', 'clob', '65535', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'tags_suscripcion');
    }
}