<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version680 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pedido', 'source', 'string', '255', array(
             ));
        $this->addColumn('pedido', 'fecha_source', 'timestamp', '25', array(
             ));
        $this->addColumn('pedido', 'utm_campaign', 'string', '255', array(
             ));
        $this->addColumn('pedido', 'utm_term', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('pedido', 'source');
        $this->removeColumn('pedido', 'fecha_source');
        $this->removeColumn('pedido', 'utm_campaign');
        $this->removeColumn('pedido', 'utm_term');
    }
}