<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version683 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

        $eshop = eshopTable::getInstance()->getById(8);
		$eshop->setDevolucionRestringidaCategorias('[7,10,11,13,16,19,21,27,24,56,64,66,99]');
		$eshop->setDevolucionRestringidaMensaje('La ropa interior, trajes de baño, faldas, monos, sacos, shorts, vestidos y accesorios no tienen cambio ni devolución, excepto por fallas del producto.');
		$eshop->save();
    }

    public function down()
    {

    }
}