<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version682 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'devolucion_restringida_categorias', 'string', '255', array());
        $this->addColumn('eshop', 'devolucion_restringida_mensaje', 'string', '255', array());
    }

    public function down()
    {
        $this->removeColumn('eshop', 'devolucion_restringida_categorias');
        $this->removeColumn('eshop', 'devolucion_restringida_mensaje');
    }
}