<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version688 extends Doctrine_Migration_Base
{
    public function up()
    {
        $eshop = eshopTable::getInstance()->getById(1);
        $eshop->setUsaMenuFlotante(true);
        $eshop->save();

        $eshop = eshopTable::getInstance()->getById(2);
        $eshop->setUsaMenuFlotante(true);
        $eshop->save();

        $eshop = eshopTable::getInstance()->getById(5);
        $eshop->setUsaMenuFlotante(true);
        $eshop->save();
    }

    public function down()
    {
    }
}

