<?php

/**
 * Baseproducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_producto
 * @property string $denominacion
 * @property clob $descripcion
 * @property clob $info_adicional
 * @property integer $id_marca
 * @property integer $id_producto_categoria
 * @property timestamp $fecha_modificacion
 * @property decimal $precio_lista
 * @property boolean $mostrar_precio_lista
 * @property decimal $precio_normal
 * @property decimal $precio_outlet
 * @property decimal $precio_deluxe
 * @property decimal $costo
 * @property decimal $peso
 * @property integer $destacar
 * @property integer $vendidos
 * @property integer $visitas
 * @property boolean $es_outlet
 * @property clob $observacion
 * @property boolean $activo
 * @property integer $id_talle_set
 * @property integer $id_producto_sticker
 * @property integer $id_categoria_ml
 * @property integer $id_eshop
 * @property integer $orden_eshop
 * @property marca $marca
 * @property productoCategoria $productoCategoria
 * @property talleSet $talleSet
 * @property productoSticker $productoSticker
 * @property categoriaMl $categoriaMl
 * @property eshop $eshop
 * @property Doctrine_Collection $productoItem
 * @property Doctrine_Collection $productoTag
 * @property Doctrine_Collection $productoCampana
 * @property Doctrine_Collection $productoImagen
 * @property Doctrine_Collection $cuponProducto
 * @property Doctrine_Collection $productoCampanaFinalizada
 * @property Doctrine_Collection $productoLog
 * @property publicacionMl $publicacionMl
 * @property Doctrine_Collection $eshopLookbookProducto
 * 
 * @method integer             getIdProducto()                Returns the current record's "id_producto" value
 * @method string              getDenominacion()              Returns the current record's "denominacion" value
 * @method clob                getDescripcion()               Returns the current record's "descripcion" value
 * @method clob                getInfoAdicional()             Returns the current record's "info_adicional" value
 * @method integer             getIdMarca()                   Returns the current record's "id_marca" value
 * @method integer             getIdProductoCategoria()       Returns the current record's "id_producto_categoria" value
 * @method timestamp           getFechaModificacion()         Returns the current record's "fecha_modificacion" value
 * @method decimal             getPrecioLista()               Returns the current record's "precio_lista" value
 * @method boolean             getMostrarPrecioLista()        Returns the current record's "mostrar_precio_lista" value
 * @method decimal             getPrecioNormal()              Returns the current record's "precio_normal" value
 * @method decimal             getPrecioOutlet()              Returns the current record's "precio_outlet" value
 * @method decimal             getPrecioDeluxe()              Returns the current record's "precio_deluxe" value
 * @method decimal             getCosto()                     Returns the current record's "costo" value
 * @method decimal             getPeso()                      Returns the current record's "peso" value
 * @method integer             getDestacar()                  Returns the current record's "destacar" value
 * @method integer             getVendidos()                  Returns the current record's "vendidos" value
 * @method integer             getVisitas()                   Returns the current record's "visitas" value
 * @method boolean             getEsOutlet()                  Returns the current record's "es_outlet" value
 * @method clob                getObservacion()               Returns the current record's "observacion" value
 * @method boolean             getActivo()                    Returns the current record's "activo" value
 * @method integer             getIdTalleSet()                Returns the current record's "id_talle_set" value
 * @method integer             getIdProductoSticker()         Returns the current record's "id_producto_sticker" value
 * @method integer             getIdCategoriaMl()             Returns the current record's "id_categoria_ml" value
 * @method integer             getIdEshop()                   Returns the current record's "id_eshop" value
 * @method integer             getOrdenEshop()                Returns the current record's "orden_eshop" value
 * @method marca               getMarca()                     Returns the current record's "marca" value
 * @method productoCategoria   getProductoCategoria()         Returns the current record's "productoCategoria" value
 * @method talleSet            getTalleSet()                  Returns the current record's "talleSet" value
 * @method productoSticker     getProductoSticker()           Returns the current record's "productoSticker" value
 * @method categoriaMl         getCategoriaMl()               Returns the current record's "categoriaMl" value
 * @method eshop               getEshop()                     Returns the current record's "eshop" value
 * @method Doctrine_Collection getProductoItem()              Returns the current record's "productoItem" collection
 * @method Doctrine_Collection getProductoTag()               Returns the current record's "productoTag" collection
 * @method Doctrine_Collection getProductoCampana()           Returns the current record's "productoCampana" collection
 * @method Doctrine_Collection getProductoImagen()            Returns the current record's "productoImagen" collection
 * @method Doctrine_Collection getCuponProducto()             Returns the current record's "cuponProducto" collection
 * @method Doctrine_Collection getProductoCampanaFinalizada() Returns the current record's "productoCampanaFinalizada" collection
 * @method Doctrine_Collection getProductoLog()               Returns the current record's "productoLog" collection
 * @method publicacionMl       getPublicacionMl()             Returns the current record's "publicacionMl" value
 * @method Doctrine_Collection getEshopLookbookProducto()     Returns the current record's "eshopLookbookProducto" collection
 * @method producto            setIdProducto()                Sets the current record's "id_producto" value
 * @method producto            setDenominacion()              Sets the current record's "denominacion" value
 * @method producto            setDescripcion()               Sets the current record's "descripcion" value
 * @method producto            setInfoAdicional()             Sets the current record's "info_adicional" value
 * @method producto            setIdMarca()                   Sets the current record's "id_marca" value
 * @method producto            setIdProductoCategoria()       Sets the current record's "id_producto_categoria" value
 * @method producto            setFechaModificacion()         Sets the current record's "fecha_modificacion" value
 * @method producto            setPrecioLista()               Sets the current record's "precio_lista" value
 * @method producto            setMostrarPrecioLista()        Sets the current record's "mostrar_precio_lista" value
 * @method producto            setPrecioNormal()              Sets the current record's "precio_normal" value
 * @method producto            setPrecioOutlet()              Sets the current record's "precio_outlet" value
 * @method producto            setPrecioDeluxe()              Sets the current record's "precio_deluxe" value
 * @method producto            setCosto()                     Sets the current record's "costo" value
 * @method producto            setPeso()                      Sets the current record's "peso" value
 * @method producto            setDestacar()                  Sets the current record's "destacar" value
 * @method producto            setVendidos()                  Sets the current record's "vendidos" value
 * @method producto            setVisitas()                   Sets the current record's "visitas" value
 * @method producto            setEsOutlet()                  Sets the current record's "es_outlet" value
 * @method producto            setObservacion()               Sets the current record's "observacion" value
 * @method producto            setActivo()                    Sets the current record's "activo" value
 * @method producto            setIdTalleSet()                Sets the current record's "id_talle_set" value
 * @method producto            setIdProductoSticker()         Sets the current record's "id_producto_sticker" value
 * @method producto            setIdCategoriaMl()             Sets the current record's "id_categoria_ml" value
 * @method producto            setIdEshop()                   Sets the current record's "id_eshop" value
 * @method producto            setOrdenEshop()                Sets the current record's "orden_eshop" value
 * @method producto            setMarca()                     Sets the current record's "marca" value
 * @method producto            setProductoCategoria()         Sets the current record's "productoCategoria" value
 * @method producto            setTalleSet()                  Sets the current record's "talleSet" value
 * @method producto            setProductoSticker()           Sets the current record's "productoSticker" value
 * @method producto            setCategoriaMl()               Sets the current record's "categoriaMl" value
 * @method producto            setEshop()                     Sets the current record's "eshop" value
 * @method producto            setProductoItem()              Sets the current record's "productoItem" collection
 * @method producto            setProductoTag()               Sets the current record's "productoTag" collection
 * @method producto            setProductoCampana()           Sets the current record's "productoCampana" collection
 * @method producto            setProductoImagen()            Sets the current record's "productoImagen" collection
 * @method producto            setCuponProducto()             Sets the current record's "cuponProducto" collection
 * @method producto            setProductoCampanaFinalizada() Sets the current record's "productoCampanaFinalizada" collection
 * @method producto            setProductoLog()               Sets the current record's "productoLog" collection
 * @method producto            setPublicacionMl()             Sets the current record's "publicacionMl" value
 * @method producto            setEshopLookbookProducto()     Sets the current record's "eshopLookbookProducto" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto');
        $this->hasColumn('id_producto', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('denominacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('info_adicional', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('id_marca', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_producto_categoria', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_modificacion', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('precio_lista', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('mostrar_precio_lista', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('precio_normal', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('precio_outlet', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('precio_deluxe', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('costo', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('peso', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('destacar', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('vendidos', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('visitas', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('es_outlet', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('observacion', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('id_talle_set', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_producto_sticker', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_categoria_ml', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('orden_eshop', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('fk_producto_marca1', array(
             'fields' => 
             array(
              0 => 'id_marca',
             ),
             ));
        $this->index('fk_producto_producto_categoria1', array(
             'fields' => 
             array(
              0 => 'id_producto_categoria',
             ),
             ));
        $this->index('ix_producto_precio_deluxe', array(
             'fields' => 
             array(
              0 => 'precio_deluxe',
             ),
             ));
        $this->index('ix_producto_visitas', array(
             'fields' => 
             array(
              0 => 'visitas',
             ),
             ));
        $this->index('ix_producto_vendidos', array(
             'fields' => 
             array(
              0 => 'vendidos',
             ),
             ));
        $this->index('fk_producto_talle_set1', array(
             'fields' => 
             array(
              0 => 'id_talle_set',
             ),
             ));
        $this->index('ix_producto_codigo', array(
             'fields' => 
             array(
              0 => 'codigo',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('marca', array(
             'local' => 'id_marca',
             'foreign' => 'id_marca',
             'owningSide' => true));

        $this->hasOne('productoCategoria', array(
             'local' => 'id_producto_categoria',
             'foreign' => 'id_producto_categoria',
             'owningSide' => true));

        $this->hasOne('talleSet', array(
             'local' => 'id_talle_set',
             'foreign' => 'id_talle_set',
             'owningSide' => true));

        $this->hasOne('productoSticker', array(
             'local' => 'id_producto_sticker',
             'foreign' => 'id_producto_sticker',
             'owningSide' => true));

        $this->hasOne('categoriaMl', array(
             'local' => 'id_categoria_ml',
             'foreign' => 'id_categoria_ml',
             'owningSide' => true));

        $this->hasOne('eshop', array(
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'owningSide' => true));

        $this->hasMany('productoItem', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('productoTag', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('productoCampana', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('productoImagen', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('cuponProducto', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('productoCampanaFinalizada', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('productoLog', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasOne('publicacionMl', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));

        $this->hasMany('eshopLookbookProducto', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto'));
    }
}