<?php

/**
 * BasereporteCronologico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_reporte_cronologico
 * @property timestamp $fecha
 * @property string $accion
 * @property integer $id_pedido
 * @property string $fuente
 * @property string $marca
 * @property string $condicion_fiscal
 * @property string $codigo_producto
 * @property string $producto
 * @property string $color
 * @property string $talle
 * @property string $categoria
 * @property string $genero
 * @property decimal $precio_deluxe
 * @property decimal $costo
 * @property integer $cantidad
 * @property decimal $bonificacion_devolucion_mp
 * @property decimal $bonificacion_devolucion_deluxe
 * @property string $bonificacion_motivo
 * @property string $bonificacion_submotivo
 * @property decimal $descuento
 * @property string $descuento_motivo
 * @property string $descuento_codigo
 * @property decimal $costo_envio
 * @property decimal $costo_envio_deluxe
 * @property string $tipo_envio
 * @property decimal $venta_db_total
 * @property decimal $total_facturado
 * @property string $cliente
 * @property string $localidad
 * @property string $provincia
 * @property string $forma_pago
 * @property integer $id_eshop
 * @property string $nombre_eshop
 * @property string $cliente_tipo_documento
 * @property string $cliente_documento
 * @property string $cliente_email
 * 
 * @method integer            getIdReporteCronologico()           Returns the current record's "id_reporte_cronologico" value
 * @method timestamp          getFecha()                          Returns the current record's "fecha" value
 * @method string             getAccion()                         Returns the current record's "accion" value
 * @method integer            getIdPedido()                       Returns the current record's "id_pedido" value
 * @method string             getFuente()                         Returns the current record's "fuente" value
 * @method string             getMarca()                          Returns the current record's "marca" value
 * @method string             getCondicionFiscal()                Returns the current record's "condicion_fiscal" value
 * @method string             getCodigoProducto()                 Returns the current record's "codigo_producto" value
 * @method string             getProducto()                       Returns the current record's "producto" value
 * @method string             getColor()                          Returns the current record's "color" value
 * @method string             getTalle()                          Returns the current record's "talle" value
 * @method string             getCategoria()                      Returns the current record's "categoria" value
 * @method string             getGenero()                         Returns the current record's "genero" value
 * @method decimal            getPrecioDeluxe()                   Returns the current record's "precio_deluxe" value
 * @method decimal            getCosto()                          Returns the current record's "costo" value
 * @method integer            getCantidad()                       Returns the current record's "cantidad" value
 * @method decimal            getBonificacionDevolucionMp()       Returns the current record's "bonificacion_devolucion_mp" value
 * @method decimal            getBonificacionDevolucionDeluxe()   Returns the current record's "bonificacion_devolucion_deluxe" value
 * @method string             getBonificacionMotivo()             Returns the current record's "bonificacion_motivo" value
 * @method string             getBonificacionSubmotivo()          Returns the current record's "bonificacion_submotivo" value
 * @method decimal            getDescuento()                      Returns the current record's "descuento" value
 * @method string             getDescuentoMotivo()                Returns the current record's "descuento_motivo" value
 * @method string             getDescuentoCodigo()                Returns the current record's "descuento_codigo" value
 * @method decimal            getCostoEnvio()                     Returns the current record's "costo_envio" value
 * @method decimal            getCostoEnvioDeluxe()               Returns the current record's "costo_envio_deluxe" value
 * @method string             getTipoEnvio()                      Returns the current record's "tipo_envio" value
 * @method decimal            getVentaDbTotal()                   Returns the current record's "venta_db_total" value
 * @method decimal            getTotalFacturado()                 Returns the current record's "total_facturado" value
 * @method string             getCliente()                        Returns the current record's "cliente" value
 * @method string             getLocalidad()                      Returns the current record's "localidad" value
 * @method string             getProvincia()                      Returns the current record's "provincia" value
 * @method string             getFormaPago()                      Returns the current record's "forma_pago" value
 * @method integer            getIdEshop()                        Returns the current record's "id_eshop" value
 * @method string             getNombreEshop()                    Returns the current record's "nombre_eshop" value
 * @method string             getClienteTipoDocumento()           Returns the current record's "cliente_tipo_documento" value
 * @method string             getClienteDocumento()               Returns the current record's "cliente_documento" value
 * @method string             getClienteEmail()                   Returns the current record's "cliente_email" value
 * @method reporteCronologico setIdReporteCronologico()           Sets the current record's "id_reporte_cronologico" value
 * @method reporteCronologico setFecha()                          Sets the current record's "fecha" value
 * @method reporteCronologico setAccion()                         Sets the current record's "accion" value
 * @method reporteCronologico setIdPedido()                       Sets the current record's "id_pedido" value
 * @method reporteCronologico setFuente()                         Sets the current record's "fuente" value
 * @method reporteCronologico setMarca()                          Sets the current record's "marca" value
 * @method reporteCronologico setCondicionFiscal()                Sets the current record's "condicion_fiscal" value
 * @method reporteCronologico setCodigoProducto()                 Sets the current record's "codigo_producto" value
 * @method reporteCronologico setProducto()                       Sets the current record's "producto" value
 * @method reporteCronologico setColor()                          Sets the current record's "color" value
 * @method reporteCronologico setTalle()                          Sets the current record's "talle" value
 * @method reporteCronologico setCategoria()                      Sets the current record's "categoria" value
 * @method reporteCronologico setGenero()                         Sets the current record's "genero" value
 * @method reporteCronologico setPrecioDeluxe()                   Sets the current record's "precio_deluxe" value
 * @method reporteCronologico setCosto()                          Sets the current record's "costo" value
 * @method reporteCronologico setCantidad()                       Sets the current record's "cantidad" value
 * @method reporteCronologico setBonificacionDevolucionMp()       Sets the current record's "bonificacion_devolucion_mp" value
 * @method reporteCronologico setBonificacionDevolucionDeluxe()   Sets the current record's "bonificacion_devolucion_deluxe" value
 * @method reporteCronologico setBonificacionMotivo()             Sets the current record's "bonificacion_motivo" value
 * @method reporteCronologico setBonificacionSubmotivo()          Sets the current record's "bonificacion_submotivo" value
 * @method reporteCronologico setDescuento()                      Sets the current record's "descuento" value
 * @method reporteCronologico setDescuentoMotivo()                Sets the current record's "descuento_motivo" value
 * @method reporteCronologico setDescuentoCodigo()                Sets the current record's "descuento_codigo" value
 * @method reporteCronologico setCostoEnvio()                     Sets the current record's "costo_envio" value
 * @method reporteCronologico setCostoEnvioDeluxe()               Sets the current record's "costo_envio_deluxe" value
 * @method reporteCronologico setTipoEnvio()                      Sets the current record's "tipo_envio" value
 * @method reporteCronologico setVentaDbTotal()                   Sets the current record's "venta_db_total" value
 * @method reporteCronologico setTotalFacturado()                 Sets the current record's "total_facturado" value
 * @method reporteCronologico setCliente()                        Sets the current record's "cliente" value
 * @method reporteCronologico setLocalidad()                      Sets the current record's "localidad" value
 * @method reporteCronologico setProvincia()                      Sets the current record's "provincia" value
 * @method reporteCronologico setFormaPago()                      Sets the current record's "forma_pago" value
 * @method reporteCronologico setIdEshop()                        Sets the current record's "id_eshop" value
 * @method reporteCronologico setNombreEshop()                    Sets the current record's "nombre_eshop" value
 * @method reporteCronologico setClienteTipoDocumento()           Sets the current record's "cliente_tipo_documento" value
 * @method reporteCronologico setClienteDocumento()               Sets the current record's "cliente_documento" value
 * @method reporteCronologico setClienteEmail()                   Sets the current record's "cliente_email" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasereporteCronologico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reporte_cronologico');
        $this->hasColumn('id_reporte_cronologico', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('accion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_pedido', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('fuente', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('marca', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('condicion_fiscal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('codigo_producto', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('producto', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('color', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('talle', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('categoria', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('genero', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('precio_deluxe', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('costo', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('bonificacion_devolucion_mp', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('bonificacion_devolucion_deluxe', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('bonificacion_motivo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bonificacion_submotivo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descuento', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('descuento_motivo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descuento_codigo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('costo_envio', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('costo_envio_deluxe', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('tipo_envio', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 3,
             ));
        $this->hasColumn('venta_db_total', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('total_facturado', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('cliente', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('localidad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('provincia', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('forma_pago', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nombre_eshop', 'string', 255, array(
             'type' => 'string',
             'default' => 'Deluxe Buys',
             'length' => 255,
             ));
        $this->hasColumn('cliente_tipo_documento', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cliente_documento', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cliente_email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}