<?php

/**
 * Basencredito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ncredito
 * @property boolean $procesada
 * @property string $CAE
 * @property string $CAE_vencimiento
 * @property integer $comprobante
 * @property string $resultado
 * @property string $entorno
 * @property decimal $importe
 * @property Doctrine_Collection $ncreditoFactura
 * @property Doctrine_Collection $ncreditoWsRequestNcredito
 * 
 * @method integer             getIdNcredito()                Returns the current record's "id_ncredito" value
 * @method boolean             getProcesada()                 Returns the current record's "procesada" value
 * @method string              getCAE()                       Returns the current record's "CAE" value
 * @method string              getCAEVencimiento()            Returns the current record's "CAE_vencimiento" value
 * @method integer             getComprobante()               Returns the current record's "comprobante" value
 * @method string              getResultado()                 Returns the current record's "resultado" value
 * @method string              getEntorno()                   Returns the current record's "entorno" value
 * @method decimal             getImporte()                   Returns the current record's "importe" value
 * @method Doctrine_Collection getNcreditoFactura()           Returns the current record's "ncreditoFactura" collection
 * @method Doctrine_Collection getNcreditoWsRequestNcredito() Returns the current record's "ncreditoWsRequestNcredito" collection
 * @method ncredito            setIdNcredito()                Sets the current record's "id_ncredito" value
 * @method ncredito            setProcesada()                 Sets the current record's "procesada" value
 * @method ncredito            setCAE()                       Sets the current record's "CAE" value
 * @method ncredito            setCAEVencimiento()            Sets the current record's "CAE_vencimiento" value
 * @method ncredito            setComprobante()               Sets the current record's "comprobante" value
 * @method ncredito            setResultado()                 Sets the current record's "resultado" value
 * @method ncredito            setEntorno()                   Sets the current record's "entorno" value
 * @method ncredito            setImporte()                   Sets the current record's "importe" value
 * @method ncredito            setNcreditoFactura()           Sets the current record's "ncreditoFactura" collection
 * @method ncredito            setNcreditoWsRequestNcredito() Sets the current record's "ncreditoWsRequestNcredito" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basencredito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ncredito');
        $this->hasColumn('id_ncredito', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('procesada', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('CAE', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('CAE_vencimiento', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('comprobante', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('resultado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 1,
             ));
        $this->hasColumn('entorno', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('importe', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ncreditoFactura', array(
             'local' => 'id_ncredito',
             'foreign' => 'id_ncredito'));

        $this->hasMany('ncreditoWsRequestNcredito', array(
             'local' => 'id_ncredito',
             'foreign' => 'id_ncredito'));
    }
}