<?php

/**
 * BasefaqCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_faq_categoria
 * @property string $denominacion
 * @property integer $id_eshop
 * @property integer $orden
 * @property eshop $eshop
 * @property Doctrine_Collection $faq
 * 
 * @method integer             getIdFaqCategoria()   Returns the current record's "id_faq_categoria" value
 * @method string              getDenominacion()     Returns the current record's "denominacion" value
 * @method integer             getIdEshop()          Returns the current record's "id_eshop" value
 * @method integer             getOrden()            Returns the current record's "orden" value
 * @method eshop               getEshop()            Returns the current record's "eshop" value
 * @method Doctrine_Collection getFaq()              Returns the current record's "faq" collection
 * @method faqCategoria        setIdFaqCategoria()   Sets the current record's "id_faq_categoria" value
 * @method faqCategoria        setDenominacion()     Sets the current record's "denominacion" value
 * @method faqCategoria        setIdEshop()          Sets the current record's "id_eshop" value
 * @method faqCategoria        setOrden()            Sets the current record's "orden" value
 * @method faqCategoria        setEshop()            Sets the current record's "eshop" value
 * @method faqCategoria        setFaq()              Sets the current record's "faq" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasefaqCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_categoria');
        $this->hasColumn('id_faq_categoria', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'zerofill' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('denominacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('eshop', array(
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'owningSide' => true));

        $this->hasMany('faq', array(
             'local' => 'id_faq_categoria',
             'foreign' => 'id_faq_categoria'));
    }
}