<?php

/**
 * Basepedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pedido
 * @property integer $id_usuario
 * @property timestamp $fecha_alta
 * @property timestamp $fecha_baja
 * @property timestamp $fecha_pago
 * @property timestamp $fecha_aviso_pago
 * @property timestamp $fecha_envio
 * @property timestamp $fecha_facturacion
 * @property timestamp $fecha_ultima_comprobacion
 * @property timestamp $fecha_limite_pago
 * @property string $nombre
 * @property string $apellido
 * @property string $tipo_documento
 * @property string $documento
 * @property string $email
 * @property string $telefono
 * @property string $celular
 * @property clob $observaciones
 * @property string $id_forma_pago
 * @property string $envio_tipo
 * @property string $envio_destinatario
 * @property string $envio_calle
 * @property string $envio_numero
 * @property string $envio_piso
 * @property string $envio_depto
 * @property string $envio_codigo_postal
 * @property integer $envio_id_sucursal
 * @property integer $envio_id_provincia
 * @property string $envio_localidad
 * @property string $envio_correo
 * @property char $envio_servicio
 * @property clob $envio_detalle
 * @property integer $envio_id_pedido_envio_pack
 * @property decimal $monto_envio
 * @property decimal $monto_envio_deluxe
 * @property decimal $monto_productos
 * @property decimal $monto_bonificacion
 * @property decimal $monto_descuento
 * @property decimal $monto_total
 * @property decimal $monto_facturacion
 * @property integer $cuotas
 * @property decimal $interes
 * @property clob $datos_pago
 * @property string $codigo_envio
 * @property clob $nota
 * @property integer $requiere_intervencion_manual
 * @property string $tipo_producto
 * @property boolean $tiene_problema_oca
 * @property integer $id_eshop
 * @property string $source
 * @property timestamp $fecha_source
 * @property string $utm_campaign
 * @property string $utm_term
 * @property usuario $usuario
 * @property formaPago $formaPago
 * @property provincia $provincia
 * @property eshop $eshop
 * @property Doctrine_Collection $invitacion
 * @property Doctrine_Collection $pedidoBonificacion
 * @property Doctrine_Collection $pedidoDescuento
 * @property Doctrine_Collection $pedidoProductoItem
 * @property Doctrine_Collection $pagoNotificacion
 * @property Doctrine_Collection $avisoPedido
 * @property factura $factura
 * @property Doctrine_Collection $faltante
 * @property Doctrine_Collection $devueltoOca
 * @property Doctrine_Collection $remitoPedido
 * @property Doctrine_Collection $premioLog
 * @property recuperoCarrito $recuperoCarrito
 * @property Doctrine_Collection $reciboEshopPedido
 * 
 * @method integer             getIdPedido()                     Returns the current record's "id_pedido" value
 * @method integer             getIdUsuario()                    Returns the current record's "id_usuario" value
 * @method timestamp           getFechaAlta()                    Returns the current record's "fecha_alta" value
 * @method timestamp           getFechaBaja()                    Returns the current record's "fecha_baja" value
 * @method timestamp           getFechaPago()                    Returns the current record's "fecha_pago" value
 * @method timestamp           getFechaAvisoPago()               Returns the current record's "fecha_aviso_pago" value
 * @method timestamp           getFechaEnvio()                   Returns the current record's "fecha_envio" value
 * @method timestamp           getFechaFacturacion()             Returns the current record's "fecha_facturacion" value
 * @method timestamp           getFechaUltimaComprobacion()      Returns the current record's "fecha_ultima_comprobacion" value
 * @method timestamp           getFechaLimitePago()              Returns the current record's "fecha_limite_pago" value
 * @method string              getNombre()                       Returns the current record's "nombre" value
 * @method string              getApellido()                     Returns the current record's "apellido" value
 * @method string              getTipoDocumento()                Returns the current record's "tipo_documento" value
 * @method string              getDocumento()                    Returns the current record's "documento" value
 * @method string              getEmail()                        Returns the current record's "email" value
 * @method string              getTelefono()                     Returns the current record's "telefono" value
 * @method string              getCelular()                      Returns the current record's "celular" value
 * @method clob                getObservaciones()                Returns the current record's "observaciones" value
 * @method string              getIdFormaPago()                  Returns the current record's "id_forma_pago" value
 * @method string              getEnvioTipo()                    Returns the current record's "envio_tipo" value
 * @method string              getEnvioDestinatario()            Returns the current record's "envio_destinatario" value
 * @method string              getEnvioCalle()                   Returns the current record's "envio_calle" value
 * @method string              getEnvioNumero()                  Returns the current record's "envio_numero" value
 * @method string              getEnvioPiso()                    Returns the current record's "envio_piso" value
 * @method string              getEnvioDepto()                   Returns the current record's "envio_depto" value
 * @method string              getEnvioCodigoPostal()            Returns the current record's "envio_codigo_postal" value
 * @method integer             getEnvioIdSucursal()              Returns the current record's "envio_id_sucursal" value
 * @method integer             getEnvioIdProvincia()             Returns the current record's "envio_id_provincia" value
 * @method string              getEnvioLocalidad()               Returns the current record's "envio_localidad" value
 * @method string              getEnvioCorreo()                  Returns the current record's "envio_correo" value
 * @method char                getEnvioServicio()                Returns the current record's "envio_servicio" value
 * @method clob                getEnvioDetalle()                 Returns the current record's "envio_detalle" value
 * @method integer             getEnvioIdPedidoEnvioPack()       Returns the current record's "envio_id_pedido_envio_pack" value
 * @method decimal             getMontoEnvio()                   Returns the current record's "monto_envio" value
 * @method decimal             getMontoEnvioDeluxe()             Returns the current record's "monto_envio_deluxe" value
 * @method decimal             getMontoProductos()               Returns the current record's "monto_productos" value
 * @method decimal             getMontoBonificacion()            Returns the current record's "monto_bonificacion" value
 * @method decimal             getMontoDescuento()               Returns the current record's "monto_descuento" value
 * @method decimal             getMontoTotal()                   Returns the current record's "monto_total" value
 * @method decimal             getMontoFacturacion()             Returns the current record's "monto_facturacion" value
 * @method integer             getCuotas()                       Returns the current record's "cuotas" value
 * @method decimal             getInteres()                      Returns the current record's "interes" value
 * @method clob                getDatosPago()                    Returns the current record's "datos_pago" value
 * @method string              getCodigoEnvio()                  Returns the current record's "codigo_envio" value
 * @method clob                getNota()                         Returns the current record's "nota" value
 * @method integer             getRequiereIntervencionManual()   Returns the current record's "requiere_intervencion_manual" value
 * @method string              getTipoProducto()                 Returns the current record's "tipo_producto" value
 * @method boolean             getTieneProblemaOca()             Returns the current record's "tiene_problema_oca" value
 * @method integer             getIdEshop()                      Returns the current record's "id_eshop" value
 * @method string              getSource()                       Returns the current record's "source" value
 * @method timestamp           getFechaSource()                  Returns the current record's "fecha_source" value
 * @method string              getUtmCampaign()                  Returns the current record's "utm_campaign" value
 * @method string              getUtmTerm()                      Returns the current record's "utm_term" value
 * @method usuario             getUsuario()                      Returns the current record's "usuario" value
 * @method formaPago           getFormaPago()                    Returns the current record's "formaPago" value
 * @method provincia           getProvincia()                    Returns the current record's "provincia" value
 * @method eshop               getEshop()                        Returns the current record's "eshop" value
 * @method Doctrine_Collection getInvitacion()                   Returns the current record's "invitacion" collection
 * @method Doctrine_Collection getPedidoBonificacion()           Returns the current record's "pedidoBonificacion" collection
 * @method Doctrine_Collection getPedidoDescuento()              Returns the current record's "pedidoDescuento" collection
 * @method Doctrine_Collection getPedidoProductoItem()           Returns the current record's "pedidoProductoItem" collection
 * @method Doctrine_Collection getPagoNotificacion()             Returns the current record's "pagoNotificacion" collection
 * @method Doctrine_Collection getAvisoPedido()                  Returns the current record's "avisoPedido" collection
 * @method factura             getFactura()                      Returns the current record's "factura" value
 * @method Doctrine_Collection getFaltante()                     Returns the current record's "faltante" collection
 * @method Doctrine_Collection getDevueltoOca()                  Returns the current record's "devueltoOca" collection
 * @method Doctrine_Collection getRemitoPedido()                 Returns the current record's "remitoPedido" collection
 * @method Doctrine_Collection getPremioLog()                    Returns the current record's "premioLog" collection
 * @method recuperoCarrito     getRecuperoCarrito()              Returns the current record's "recuperoCarrito" value
 * @method Doctrine_Collection getReciboEshopPedido()            Returns the current record's "reciboEshopPedido" collection
 * @method pedido              setIdPedido()                     Sets the current record's "id_pedido" value
 * @method pedido              setIdUsuario()                    Sets the current record's "id_usuario" value
 * @method pedido              setFechaAlta()                    Sets the current record's "fecha_alta" value
 * @method pedido              setFechaBaja()                    Sets the current record's "fecha_baja" value
 * @method pedido              setFechaPago()                    Sets the current record's "fecha_pago" value
 * @method pedido              setFechaAvisoPago()               Sets the current record's "fecha_aviso_pago" value
 * @method pedido              setFechaEnvio()                   Sets the current record's "fecha_envio" value
 * @method pedido              setFechaFacturacion()             Sets the current record's "fecha_facturacion" value
 * @method pedido              setFechaUltimaComprobacion()      Sets the current record's "fecha_ultima_comprobacion" value
 * @method pedido              setFechaLimitePago()              Sets the current record's "fecha_limite_pago" value
 * @method pedido              setNombre()                       Sets the current record's "nombre" value
 * @method pedido              setApellido()                     Sets the current record's "apellido" value
 * @method pedido              setTipoDocumento()                Sets the current record's "tipo_documento" value
 * @method pedido              setDocumento()                    Sets the current record's "documento" value
 * @method pedido              setEmail()                        Sets the current record's "email" value
 * @method pedido              setTelefono()                     Sets the current record's "telefono" value
 * @method pedido              setCelular()                      Sets the current record's "celular" value
 * @method pedido              setObservaciones()                Sets the current record's "observaciones" value
 * @method pedido              setIdFormaPago()                  Sets the current record's "id_forma_pago" value
 * @method pedido              setEnvioTipo()                    Sets the current record's "envio_tipo" value
 * @method pedido              setEnvioDestinatario()            Sets the current record's "envio_destinatario" value
 * @method pedido              setEnvioCalle()                   Sets the current record's "envio_calle" value
 * @method pedido              setEnvioNumero()                  Sets the current record's "envio_numero" value
 * @method pedido              setEnvioPiso()                    Sets the current record's "envio_piso" value
 * @method pedido              setEnvioDepto()                   Sets the current record's "envio_depto" value
 * @method pedido              setEnvioCodigoPostal()            Sets the current record's "envio_codigo_postal" value
 * @method pedido              setEnvioIdSucursal()              Sets the current record's "envio_id_sucursal" value
 * @method pedido              setEnvioIdProvincia()             Sets the current record's "envio_id_provincia" value
 * @method pedido              setEnvioLocalidad()               Sets the current record's "envio_localidad" value
 * @method pedido              setEnvioCorreo()                  Sets the current record's "envio_correo" value
 * @method pedido              setEnvioServicio()                Sets the current record's "envio_servicio" value
 * @method pedido              setEnvioDetalle()                 Sets the current record's "envio_detalle" value
 * @method pedido              setEnvioIdPedidoEnvioPack()       Sets the current record's "envio_id_pedido_envio_pack" value
 * @method pedido              setMontoEnvio()                   Sets the current record's "monto_envio" value
 * @method pedido              setMontoEnvioDeluxe()             Sets the current record's "monto_envio_deluxe" value
 * @method pedido              setMontoProductos()               Sets the current record's "monto_productos" value
 * @method pedido              setMontoBonificacion()            Sets the current record's "monto_bonificacion" value
 * @method pedido              setMontoDescuento()               Sets the current record's "monto_descuento" value
 * @method pedido              setMontoTotal()                   Sets the current record's "monto_total" value
 * @method pedido              setMontoFacturacion()             Sets the current record's "monto_facturacion" value
 * @method pedido              setCuotas()                       Sets the current record's "cuotas" value
 * @method pedido              setInteres()                      Sets the current record's "interes" value
 * @method pedido              setDatosPago()                    Sets the current record's "datos_pago" value
 * @method pedido              setCodigoEnvio()                  Sets the current record's "codigo_envio" value
 * @method pedido              setNota()                         Sets the current record's "nota" value
 * @method pedido              setRequiereIntervencionManual()   Sets the current record's "requiere_intervencion_manual" value
 * @method pedido              setTipoProducto()                 Sets the current record's "tipo_producto" value
 * @method pedido              setTieneProblemaOca()             Sets the current record's "tiene_problema_oca" value
 * @method pedido              setIdEshop()                      Sets the current record's "id_eshop" value
 * @method pedido              setSource()                       Sets the current record's "source" value
 * @method pedido              setFechaSource()                  Sets the current record's "fecha_source" value
 * @method pedido              setUtmCampaign()                  Sets the current record's "utm_campaign" value
 * @method pedido              setUtmTerm()                      Sets the current record's "utm_term" value
 * @method pedido              setUsuario()                      Sets the current record's "usuario" value
 * @method pedido              setFormaPago()                    Sets the current record's "formaPago" value
 * @method pedido              setProvincia()                    Sets the current record's "provincia" value
 * @method pedido              setEshop()                        Sets the current record's "eshop" value
 * @method pedido              setInvitacion()                   Sets the current record's "invitacion" collection
 * @method pedido              setPedidoBonificacion()           Sets the current record's "pedidoBonificacion" collection
 * @method pedido              setPedidoDescuento()              Sets the current record's "pedidoDescuento" collection
 * @method pedido              setPedidoProductoItem()           Sets the current record's "pedidoProductoItem" collection
 * @method pedido              setPagoNotificacion()             Sets the current record's "pagoNotificacion" collection
 * @method pedido              setAvisoPedido()                  Sets the current record's "avisoPedido" collection
 * @method pedido              setFactura()                      Sets the current record's "factura" value
 * @method pedido              setFaltante()                     Sets the current record's "faltante" collection
 * @method pedido              setDevueltoOca()                  Sets the current record's "devueltoOca" collection
 * @method pedido              setRemitoPedido()                 Sets the current record's "remitoPedido" collection
 * @method pedido              setPremioLog()                    Sets the current record's "premioLog" collection
 * @method pedido              setRecuperoCarrito()              Sets the current record's "recuperoCarrito" value
 * @method pedido              setReciboEshopPedido()            Sets the current record's "reciboEshopPedido" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepedido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pedido');
        $this->hasColumn('id_pedido', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_alta', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_baja', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_pago', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_aviso_pago', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_envio', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_facturacion', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_ultima_comprobacion', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_limite_pago', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('apellido', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('tipo_documento', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('documento', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('telefono', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('celular', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('observaciones', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('id_forma_pago', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 5,
             ));
        $this->hasColumn('envio_tipo', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 3,
             ));
        $this->hasColumn('envio_destinatario', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('envio_calle', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('envio_numero', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('envio_piso', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
        $this->hasColumn('envio_depto', 'string', 4, array(
             'type' => 'string',
             'length' => 4,
             ));
        $this->hasColumn('envio_codigo_postal', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('envio_id_sucursal', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('envio_id_provincia', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('envio_localidad', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('envio_correo', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('envio_servicio', 'char', 1, array(
             'type' => 'char',
             'length' => 1,
             ));
        $this->hasColumn('envio_detalle', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('envio_id_pedido_envio_pack', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('monto_envio', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('monto_envio_deluxe', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('monto_productos', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('monto_bonificacion', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('monto_descuento', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('monto_total', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('monto_facturacion', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('cuotas', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('interes', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('datos_pago', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('codigo_envio', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nota', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('requiere_intervencion_manual', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('tipo_producto', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 5,
             ));
        $this->hasColumn('tiene_problema_oca', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fecha_source', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('utm_campaign', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('utm_term', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('fk_pedido_usuario1', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
        $this->index('fk_pedido_forma_pago1', array(
             'fields' => 
             array(
              0 => 'id_forma_pago',
             ),
             ));
        $this->index('fk_pedido_provincia1', array(
             'fields' => 
             array(
              0 => 'envio_id_provincia',
             ),
             ));
        $this->index('ix_pedido_codigo_envio', array(
             'fields' => 
             array(
              0 => 'codigo_envio',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario',
             'owningSide' => true));

        $this->hasOne('formaPago', array(
             'local' => 'id_forma_pago',
             'foreign' => 'id_forma_pago',
             'owningSide' => true));

        $this->hasOne('provincia', array(
             'local' => 'envio_id_provincia',
             'foreign' => 'id_provincia',
             'owningSide' => true));

        $this->hasOne('eshop', array(
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'owningSide' => true));

        $this->hasMany('invitacion', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido_realizado'));

        $this->hasMany('pedidoBonificacion', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('pedidoDescuento', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('pedidoProductoItem', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('pagoNotificacion', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('avisoPedido', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasOne('factura', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('faltante', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('devueltoOca', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('remitoPedido', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('premioLog', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasOne('recuperoCarrito', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $this->hasMany('reciboEshopPedido', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_alta',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}