<?php

/**
 * BaseeshopHomeMultimedia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_eshop_home_multimedia
 * @property integer $id_eshop_home
 * @property string $indice
 * @property string $link
 * @property boolean $es_video
 * @property eshopHome $eshopHome
 * 
 * @method integer             getIdEshopHomeMultimedia()    Returns the current record's "id_eshop_home_multimedia" value
 * @method integer             getIdEshopHome()              Returns the current record's "id_eshop_home" value
 * @method string              getIndice()                   Returns the current record's "indice" value
 * @method string              getLink()                     Returns the current record's "link" value
 * @method boolean             getEsVideo()                  Returns the current record's "es_video" value
 * @method eshopHome           getEshopHome()                Returns the current record's "eshopHome" value
 * @method eshopHomeMultimedia setIdEshopHomeMultimedia()    Sets the current record's "id_eshop_home_multimedia" value
 * @method eshopHomeMultimedia setIdEshopHome()              Sets the current record's "id_eshop_home" value
 * @method eshopHomeMultimedia setIndice()                   Sets the current record's "indice" value
 * @method eshopHomeMultimedia setLink()                     Sets the current record's "link" value
 * @method eshopHomeMultimedia setEsVideo()                  Sets the current record's "es_video" value
 * @method eshopHomeMultimedia setEshopHome()                Sets the current record's "eshopHome" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseeshopHomeMultimedia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eshop_home_multimedia');
        $this->hasColumn('id_eshop_home_multimedia', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_eshop_home', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('indice', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('es_video', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('eshopHome', array(
             'local' => 'id_eshop_home',
             'foreign' => 'id_eshop_home',
             'owningSide' => true));
    }
}