<?php

/**
 * BasepremioLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_premio_log
 * @property integer $id_premio
 * @property integer $id_bonificacion
 * @property integer $id_pedido
 * @property premio $premio
 * @property bonificacion $bonificacion
 * @property pedido $pedido
 * 
 * @method integer      getIdPremioLog()     Returns the current record's "id_premio_log" value
 * @method integer      getIdPremio()        Returns the current record's "id_premio" value
 * @method integer      getIdBonificacion()  Returns the current record's "id_bonificacion" value
 * @method integer      getIdPedido()        Returns the current record's "id_pedido" value
 * @method premio       getPremio()          Returns the current record's "premio" value
 * @method bonificacion getBonificacion()    Returns the current record's "bonificacion" value
 * @method pedido       getPedido()          Returns the current record's "pedido" value
 * @method premioLog    setIdPremioLog()     Sets the current record's "id_premio_log" value
 * @method premioLog    setIdPremio()        Sets the current record's "id_premio" value
 * @method premioLog    setIdBonificacion()  Sets the current record's "id_bonificacion" value
 * @method premioLog    setIdPedido()        Sets the current record's "id_pedido" value
 * @method premioLog    setPremio()          Sets the current record's "premio" value
 * @method premioLog    setBonificacion()    Sets the current record's "bonificacion" value
 * @method premioLog    setPedido()          Sets the current record's "pedido" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasepremioLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('premio_log');
        $this->hasColumn('id_premio_log', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_premio', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_bonificacion', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_pedido', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_premio_log_premio1', array(
             'fields' => 
             array(
              0 => 'id_premio',
             ),
             ));
        $this->index('fk_premio_log_bonificacion1', array(
             'fields' => 
             array(
              0 => 'id_bonificacion',
             ),
             ));
        $this->index('fk_premio_log_pedido1', array(
             'fields' => 
             array(
              0 => 'id_pedido',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('premio', array(
             'local' => 'id_premio',
             'foreign' => 'id_premio',
             'owningSide' => true));

        $this->hasOne('bonificacion', array(
             'local' => 'id_bonificacion',
             'foreign' => 'id_bonificacion',
             'owningSide' => true));

        $this->hasOne('pedido', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido',
             'owningSide' => true));
    }
}