<?php

/**
 * BaseproductoImagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_producto_imagen
 * @property integer $id_producto
 * @property integer $orden
 * @property producto $producto
 * 
 * @method integer        getIdProductoImagen()   Returns the current record's "id_producto_imagen" value
 * @method integer        getIdProducto()         Returns the current record's "id_producto" value
 * @method integer        getOrden()              Returns the current record's "orden" value
 * @method producto       getProducto()           Returns the current record's "producto" value
 * @method productoImagen setIdProductoImagen()   Sets the current record's "id_producto_imagen" value
 * @method productoImagen setIdProducto()         Sets the current record's "id_producto" value
 * @method productoImagen setOrden()              Sets the current record's "orden" value
 * @method productoImagen setProducto()           Sets the current record's "producto" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseproductoImagen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_imagen');
        $this->hasColumn('id_producto_imagen', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_producto', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('orden', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));


        $this->index('fk_producto_imagen_producto1', array(
             'fields' => 
             array(
              0 => 'id_producto',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('producto', array(
             'local' => 'id_producto',
             'foreign' => 'id_producto',
             'owningSide' => true));
    }
}