<?php

/**
 * BaseavisoPedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_aviso_pedido
 * @property string $id_tipo_aviso_pedido
 * @property timestamp $fecha
 * @property integer $id_pedido
 * @property string $hash
 * @property tipoAvisoPedido $tipoAvisoPedido
 * @property pedido $pedido
 * 
 * @method integer         getIdAvisoPedido()        Returns the current record's "id_aviso_pedido" value
 * @method string          getIdTipoAvisoPedido()    Returns the current record's "id_tipo_aviso_pedido" value
 * @method timestamp       getFecha()                Returns the current record's "fecha" value
 * @method integer         getIdPedido()             Returns the current record's "id_pedido" value
 * @method string          getHash()                 Returns the current record's "hash" value
 * @method tipoAvisoPedido getTipoAvisoPedido()      Returns the current record's "tipoAvisoPedido" value
 * @method pedido          getPedido()               Returns the current record's "pedido" value
 * @method avisoPedido     setIdAvisoPedido()        Sets the current record's "id_aviso_pedido" value
 * @method avisoPedido     setIdTipoAvisoPedido()    Sets the current record's "id_tipo_aviso_pedido" value
 * @method avisoPedido     setFecha()                Sets the current record's "fecha" value
 * @method avisoPedido     setIdPedido()             Sets the current record's "id_pedido" value
 * @method avisoPedido     setHash()                 Sets the current record's "hash" value
 * @method avisoPedido     setTipoAvisoPedido()      Sets the current record's "tipoAvisoPedido" value
 * @method avisoPedido     setPedido()               Sets the current record's "pedido" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseavisoPedido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aviso_pedido');
        $this->hasColumn('id_aviso_pedido', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_aviso_pedido', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('id_pedido', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('hash', 'string', 32, array(
             'type' => 'string',
             'fixed' => 1,
             'unique' => true,
             'length' => 32,
             ));


        $this->index('fk_aviso_pedido_tipo_aviso_pedido1', array(
             'fields' => 
             array(
              0 => 'id_tipo_aviso_pedido',
             ),
             ));
        $this->index('fk_aviso_pedido_pedido1', array(
             'fields' => 
             array(
              0 => 'id_pedido',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tipoAvisoPedido', array(
             'local' => 'id_tipo_aviso_pedido',
             'foreign' => 'id_tipo_aviso_pedido',
             'owningSide' => true));

        $this->hasOne('pedido', array(
             'local' => 'id_pedido',
             'foreign' => 'id_pedido',
             'owningSide' => true));
    }
}