<?php

/**
 * Baseprovincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_provincia
 * @property string $nombre
 * @property string $id_mercado_libre
 * @property char $iso
 * @property boolean $activa
 * @property Doctrine_Collection $provincia
 * @property Doctrine_Collection $codigoPostal
 * 
 * @method integer             getIdProvincia()      Returns the current record's "id_provincia" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getIdMercadoLibre()   Returns the current record's "id_mercado_libre" value
 * @method char                getIso()              Returns the current record's "iso" value
 * @method boolean             getActiva()           Returns the current record's "activa" value
 * @method Doctrine_Collection getProvincia()        Returns the current record's "provincia" collection
 * @method Doctrine_Collection getCodigoPostal()     Returns the current record's "codigoPostal" collection
 * @method provincia           setIdProvincia()      Sets the current record's "id_provincia" value
 * @method provincia           setNombre()           Sets the current record's "nombre" value
 * @method provincia           setIdMercadoLibre()   Sets the current record's "id_mercado_libre" value
 * @method provincia           setIso()              Sets the current record's "iso" value
 * @method provincia           setActiva()           Sets the current record's "activa" value
 * @method provincia           setProvincia()        Sets the current record's "provincia" collection
 * @method provincia           setCodigoPostal()     Sets the current record's "codigoPostal" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprovincia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('provincia');
        $this->hasColumn('id_provincia', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_mercado_libre', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('iso', 'char', 1, array(
             'type' => 'char',
             'length' => 1,
             ));
        $this->hasColumn('activa', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('direccionEnvio as provincia', array(
             'local' => 'id_provincia',
             'foreign' => 'id_provincia'));

        $this->hasMany('codigoPostal', array(
             'local' => 'id_provincia',
             'foreign' => 'id_provincia'));
    }
}