<?php

/**
 * Basecuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cuota
 * @property string $id_banco
 * @property integer $id_tarjeta
 * @property integer $cuotas
 * @property float $multiplicador
 * @property banco $banco
 * @property tarjeta $tarjeta
 * 
 * @method integer getIdCuota()       Returns the current record's "id_cuota" value
 * @method string  getIdBanco()       Returns the current record's "id_banco" value
 * @method integer getIdTarjeta()     Returns the current record's "id_tarjeta" value
 * @method integer getCuotas()        Returns the current record's "cuotas" value
 * @method float   getMultiplicador() Returns the current record's "multiplicador" value
 * @method banco   getBanco()         Returns the current record's "banco" value
 * @method tarjeta getTarjeta()       Returns the current record's "tarjeta" value
 * @method cuota   setIdCuota()       Sets the current record's "id_cuota" value
 * @method cuota   setIdBanco()       Sets the current record's "id_banco" value
 * @method cuota   setIdTarjeta()     Sets the current record's "id_tarjeta" value
 * @method cuota   setCuotas()        Sets the current record's "cuotas" value
 * @method cuota   setMultiplicador() Sets the current record's "multiplicador" value
 * @method cuota   setBanco()         Sets the current record's "banco" value
 * @method cuota   setTarjeta()       Sets the current record's "tarjeta" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecuota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuota');
        $this->hasColumn('id_cuota', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_banco', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_tarjeta', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cuotas', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('multiplicador', 'float', null, array(
             'type' => 'float',
             ));


        $this->index('fk_cuota_banco1', array(
             'fields' => 
             array(
              0 => 'id_banco',
             ),
             ));
        $this->index('fk_cuota_tarjeta1', array(
             'fields' => 
             array(
              0 => 'id_tarjeta',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('banco', array(
             'local' => 'id_banco',
             'foreign' => 'id_banco',
             'owningSide' => true));

        $this->hasOne('tarjeta', array(
             'local' => 'id_tarjeta',
             'foreign' => 'id_tarjeta',
             'owningSide' => true));
    }
}