<?php

/**
 * BaseeshopImagenCampaign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_eshop_imagen_campaign
 * @property integer $id_eshop
 * @property boolean $slide
 * @property boolean $activo
 * @property integer $orden
 * @property eshop $eshop
 * 
 * @method integer             getIdEshopImagenCampaign()    Returns the current record's "id_eshop_imagen_campaign" value
 * @method integer             getIdEshop()                  Returns the current record's "id_eshop" value
 * @method boolean             getSlide()                    Returns the current record's "slide" value
 * @method boolean             getActivo()                   Returns the current record's "activo" value
 * @method integer             getOrden()                    Returns the current record's "orden" value
 * @method eshop               getEshop()                    Returns the current record's "eshop" value
 * @method eshopImagenCampaign setIdEshopImagenCampaign()    Sets the current record's "id_eshop_imagen_campaign" value
 * @method eshopImagenCampaign setIdEshop()                  Sets the current record's "id_eshop" value
 * @method eshopImagenCampaign setSlide()                    Sets the current record's "slide" value
 * @method eshopImagenCampaign setActivo()                   Sets the current record's "activo" value
 * @method eshopImagenCampaign setOrden()                    Sets the current record's "orden" value
 * @method eshopImagenCampaign setEshop()                    Sets the current record's "eshop" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseeshopImagenCampaign extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eshop_imagen_campaign');
        $this->hasColumn('id_eshop_imagen_campaign', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('slide', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('orden', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('eshop', array(
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'owningSide' => true));
    }
}