<?php

/**
 * BasencreditoWsRequestNcredito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ncredito
 * @property integer $id_ncredito_ws_request
 * @property ncredito $ncredito
 * @property ncreditoWsRequest $ncreditoWsRequest
 * 
 * @method integer                   getIdNcredito()             Returns the current record's "id_ncredito" value
 * @method integer                   getIdNcreditoWsRequest()    Returns the current record's "id_ncredito_ws_request" value
 * @method ncredito                  getNcredito()               Returns the current record's "ncredito" value
 * @method ncreditoWsRequest         getNcreditoWsRequest()      Returns the current record's "ncreditoWsRequest" value
 * @method ncreditoWsRequestNcredito setIdNcredito()             Sets the current record's "id_ncredito" value
 * @method ncreditoWsRequestNcredito setIdNcreditoWsRequest()    Sets the current record's "id_ncredito_ws_request" value
 * @method ncreditoWsRequestNcredito setNcredito()               Sets the current record's "ncredito" value
 * @method ncreditoWsRequestNcredito setNcreditoWsRequest()      Sets the current record's "ncreditoWsRequest" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasencreditoWsRequestNcredito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ncredito_ws_request_ncredito');
        $this->hasColumn('id_ncredito', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_ncredito_ws_request', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_ncredito_has_ncredito_ws_request_ncredito_ws_r1', array(
             'fields' => 
             array(
              0 => 'id_ncredito_ws_request',
             ),
             ));
        $this->index('fk_ncredito_has_ncredito_ws_request_ncredito1', array(
             'fields' => 
             array(
              0 => 'id_ncredito',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ncredito', array(
             'local' => 'id_ncredito',
             'foreign' => 'id_ncredito',
             'owningSide' => true));

        $this->hasOne('ncreditoWsRequest', array(
             'local' => 'id_ncredito_ws_request',
             'foreign' => 'id_ncredito_ws_request',
             'owningSide' => true));
    }
}