<?php

/**
 * BasecategoriaMl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_categoria_ml
 * @property integer $id_categoria_ml_padre
 * @property string $denominacion
 * @property string $id_externo
 * @property boolean $tiene_hijos
 * @property string $attribute_types
 * @property categoriaMl $categoriaMl
 * @property Doctrine_Collection $producto
 * @property Doctrine_Collection $categoriaMlPadre
 * 
 * @method integer             getIdCategoriaMl()         Returns the current record's "id_categoria_ml" value
 * @method integer             getIdCategoriaMlPadre()    Returns the current record's "id_categoria_ml_padre" value
 * @method string              getDenominacion()          Returns the current record's "denominacion" value
 * @method string              getIdExterno()             Returns the current record's "id_externo" value
 * @method boolean             getTieneHijos()            Returns the current record's "tiene_hijos" value
 * @method string              getAttributeTypes()        Returns the current record's "attribute_types" value
 * @method categoriaMl         getCategoriaMl()           Returns the current record's "categoriaMl" value
 * @method Doctrine_Collection getProducto()              Returns the current record's "producto" collection
 * @method Doctrine_Collection getCategoriaMlPadre()      Returns the current record's "categoriaMlPadre" collection
 * @method categoriaMl         setIdCategoriaMl()         Sets the current record's "id_categoria_ml" value
 * @method categoriaMl         setIdCategoriaMlPadre()    Sets the current record's "id_categoria_ml_padre" value
 * @method categoriaMl         setDenominacion()          Sets the current record's "denominacion" value
 * @method categoriaMl         setIdExterno()             Sets the current record's "id_externo" value
 * @method categoriaMl         setTieneHijos()            Sets the current record's "tiene_hijos" value
 * @method categoriaMl         setAttributeTypes()        Sets the current record's "attribute_types" value
 * @method categoriaMl         setCategoriaMl()           Sets the current record's "categoriaMl" value
 * @method categoriaMl         setProducto()              Sets the current record's "producto" collection
 * @method categoriaMl         setCategoriaMlPadre()      Sets the current record's "categoriaMlPadre" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasecategoriaMl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria_ml');
        $this->hasColumn('id_categoria_ml', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_categoria_ml_padre', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('denominacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_externo', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('tiene_hijos', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('attribute_types', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));


        $this->index('fk_categoria_ml_id_categoria_ml_padre', array(
             'fields' => 
             array(
              0 => 'id_categoria_ml_padre',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categoriaMl', array(
             'local' => 'id_categoria_ml',
             'foreign' => 'id_categoria_ml_padre',
             'owningSide' => true));

        $this->hasMany('producto', array(
             'local' => 'id_categoria_ml',
             'foreign' => 'id_categoria_ml'));

        $this->hasMany('categoriaMl as categoriaMlPadre', array(
             'local' => 'id_categoria_ml_padre',
             'foreign' => 'id_categoria_ml'));
    }
}