<?php

/**
 * BasecampanaMarca
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_campana
 * @property integer $id_marca
 * @property integer $id_comercial
 * @property float $comision_comercial
 * @property integer $apertura_marca
 * @property string $email_orden_compra
 * @property string $telefono_orden_compra
 * @property boolean $enviar_aviso_orden_compra
 * @property date $fecha_estimada_entrega
 * @property clob $comentario_marca
 * @property clob $comentario_interno
 * @property timestamp $ultimo_envio
 * @property string $hash
 * @property decimal $costo_total
 * @property boolean $pagada
 * @property campana $campana
 * @property marca $marca
 * @property comercial $comercial
 * 
 * @method integer      getIdCampana()                 Returns the current record's "id_campana" value
 * @method integer      getIdMarca()                   Returns the current record's "id_marca" value
 * @method integer      getIdComercial()               Returns the current record's "id_comercial" value
 * @method float        getComisionComercial()         Returns the current record's "comision_comercial" value
 * @method integer      getAperturaMarca()             Returns the current record's "apertura_marca" value
 * @method string       getEmailOrdenCompra()          Returns the current record's "email_orden_compra" value
 * @method string       getTelefonoOrdenCompra()       Returns the current record's "telefono_orden_compra" value
 * @method boolean      getEnviarAvisoOrdenCompra()    Returns the current record's "enviar_aviso_orden_compra" value
 * @method date         getFechaEstimadaEntrega()      Returns the current record's "fecha_estimada_entrega" value
 * @method clob         getComentarioMarca()           Returns the current record's "comentario_marca" value
 * @method clob         getComentarioInterno()         Returns the current record's "comentario_interno" value
 * @method timestamp    getUltimoEnvio()               Returns the current record's "ultimo_envio" value
 * @method string       getHash()                      Returns the current record's "hash" value
 * @method decimal      getCostoTotal()                Returns the current record's "costo_total" value
 * @method boolean      getPagada()                    Returns the current record's "pagada" value
 * @method campana      getCampana()                   Returns the current record's "campana" value
 * @method marca        getMarca()                     Returns the current record's "marca" value
 * @method comercial    getComercial()                 Returns the current record's "comercial" value
 * @method campanaMarca setIdCampana()                 Sets the current record's "id_campana" value
 * @method campanaMarca setIdMarca()                   Sets the current record's "id_marca" value
 * @method campanaMarca setIdComercial()               Sets the current record's "id_comercial" value
 * @method campanaMarca setComisionComercial()         Sets the current record's "comision_comercial" value
 * @method campanaMarca setAperturaMarca()             Sets the current record's "apertura_marca" value
 * @method campanaMarca setEmailOrdenCompra()          Sets the current record's "email_orden_compra" value
 * @method campanaMarca setTelefonoOrdenCompra()       Sets the current record's "telefono_orden_compra" value
 * @method campanaMarca setEnviarAvisoOrdenCompra()    Sets the current record's "enviar_aviso_orden_compra" value
 * @method campanaMarca setFechaEstimadaEntrega()      Sets the current record's "fecha_estimada_entrega" value
 * @method campanaMarca setComentarioMarca()           Sets the current record's "comentario_marca" value
 * @method campanaMarca setComentarioInterno()         Sets the current record's "comentario_interno" value
 * @method campanaMarca setUltimoEnvio()               Sets the current record's "ultimo_envio" value
 * @method campanaMarca setHash()                      Sets the current record's "hash" value
 * @method campanaMarca setCostoTotal()                Sets the current record's "costo_total" value
 * @method campanaMarca setPagada()                    Sets the current record's "pagada" value
 * @method campanaMarca setCampana()                   Sets the current record's "campana" value
 * @method campanaMarca setMarca()                     Sets the current record's "marca" value
 * @method campanaMarca setComercial()                 Sets the current record's "comercial" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasecampanaMarca extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campana_marca');
        $this->hasColumn('id_campana', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_marca', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_comercial', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('comision_comercial', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('apertura_marca', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('email_orden_compra', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono_orden_compra', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('enviar_aviso_orden_compra', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('fecha_estimada_entrega', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('comentario_marca', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('comentario_interno', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('ultimo_envio', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('hash', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('costo_total', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 12,
             ));
        $this->hasColumn('pagada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));


        $this->index('fk_campana_has_marca_marca1', array(
             'fields' => 
             array(
              0 => 'id_marca',
             ),
             ));
        $this->index('fk_campana_has_marca_campana1', array(
             'fields' => 
             array(
              0 => 'id_campana',
             ),
             ));
        $this->index('fk_campana_marca_comercial1', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('campana', array(
             'local' => 'id_campana',
             'foreign' => 'id_campana',
             'owningSide' => true));

        $this->hasOne('marca', array(
             'local' => 'id_marca',
             'foreign' => 'id_marca',
             'owningSide' => true));

        $this->hasOne('comercial', array(
             'local' => 'id_comercial',
             'foreign' => 'id_comercial',
             'owningSide' => true));
    }
}