<?php

/**
 * BaseformaPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_forma_pago
 * @property string $denominacion
 * @property Doctrine_Collection $pedido
 * @property Doctrine_Collection $pagoNotificacion
 * @property Doctrine_Collection $promoPago
 * 
 * @method string              getIdFormaPago()      Returns the current record's "id_forma_pago" value
 * @method string              getDenominacion()     Returns the current record's "denominacion" value
 * @method Doctrine_Collection getPedido()           Returns the current record's "pedido" collection
 * @method Doctrine_Collection getPagoNotificacion() Returns the current record's "pagoNotificacion" collection
 * @method Doctrine_Collection getPromoPago()        Returns the current record's "promoPago" collection
 * @method formaPago           setIdFormaPago()      Sets the current record's "id_forma_pago" value
 * @method formaPago           setDenominacion()     Sets the current record's "denominacion" value
 * @method formaPago           setPedido()           Sets the current record's "pedido" collection
 * @method formaPago           setPagoNotificacion() Sets the current record's "pagoNotificacion" collection
 * @method formaPago           setPromoPago()        Sets the current record's "promoPago" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseformaPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forma_pago');
        $this->hasColumn('id_forma_pago', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('denominacion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('pedido', array(
             'local' => 'id_forma_pago',
             'foreign' => 'id_forma_pago'));

        $this->hasMany('pagoNotificacion', array(
             'local' => 'id_forma_pago',
             'foreign' => 'id_forma_pago'));

        $this->hasMany('promoPago', array(
             'local' => 'id_forma_pago',
             'foreign' => 'id_forma_pago'));
    }
}