<?php

/**
 * BasewaitingList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_waiting_list
 * @property integer $id_usuario
 * @property timestamp $fecha
 * @property integer $id_producto_item
 * @property integer $cantidad
 * @property usuario $usuario
 * @property productoItem $productoItem
 * 
 * @method integer      getIdWaitingList()    Returns the current record's "id_waiting_list" value
 * @method integer      getIdUsuario()        Returns the current record's "id_usuario" value
 * @method timestamp    getFecha()            Returns the current record's "fecha" value
 * @method integer      getIdProductoItem()   Returns the current record's "id_producto_item" value
 * @method integer      getCantidad()         Returns the current record's "cantidad" value
 * @method usuario      getUsuario()          Returns the current record's "usuario" value
 * @method productoItem getProductoItem()     Returns the current record's "productoItem" value
 * @method waitingList  setIdWaitingList()    Sets the current record's "id_waiting_list" value
 * @method waitingList  setIdUsuario()        Sets the current record's "id_usuario" value
 * @method waitingList  setFecha()            Sets the current record's "fecha" value
 * @method waitingList  setIdProductoItem()   Sets the current record's "id_producto_item" value
 * @method waitingList  setCantidad()         Sets the current record's "cantidad" value
 * @method waitingList  setUsuario()          Sets the current record's "usuario" value
 * @method waitingList  setProductoItem()     Sets the current record's "productoItem" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasewaitingList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('waiting_list');
        $this->hasColumn('id_waiting_list', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('id_producto_item', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('fk_wait_list_usuario1', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
        $this->index('fk_waiting_list_producto_item1', array(
             'fields' => 
             array(
              0 => 'id_producto_item',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario',
             'owningSide' => true));

        $this->hasOne('productoItem', array(
             'local' => 'id_producto_item',
             'foreign' => 'id_producto_item',
             'owningSide' => true));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}