<?php

/**
 * BaseeshopHome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_eshop_home
 * @property integer $id_eshop
 * @property string $denominacion
 * @property char $tipo
 * @property timestamp $vigencia_desde
 * @property timestamp $vigencia_hasta
 * @property integer $orden
 * @property boolean $activo
 * @property string $texto
 * @property eshop $eshop
 * @property Doctrine_Collection $eshopHomeMultimedia
 * 
 * @method integer             getIdEshopHome()         Returns the current record's "id_eshop_home" value
 * @method integer             getIdEshop()             Returns the current record's "id_eshop" value
 * @method string              getDenominacion()        Returns the current record's "denominacion" value
 * @method char                getTipo()                Returns the current record's "tipo" value
 * @method timestamp           getVigenciaDesde()       Returns the current record's "vigencia_desde" value
 * @method timestamp           getVigenciaHasta()       Returns the current record's "vigencia_hasta" value
 * @method integer             getOrden()               Returns the current record's "orden" value
 * @method boolean             getActivo()              Returns the current record's "activo" value
 * @method string              getTexto()               Returns the current record's "texto" value
 * @method eshop               getEshop()               Returns the current record's "eshop" value
 * @method Doctrine_Collection getEshopHomeMultimedia() Returns the current record's "eshopHomeMultimedia" collection
 * @method eshopHome           setIdEshopHome()         Sets the current record's "id_eshop_home" value
 * @method eshopHome           setIdEshop()             Sets the current record's "id_eshop" value
 * @method eshopHome           setDenominacion()        Sets the current record's "denominacion" value
 * @method eshopHome           setTipo()                Sets the current record's "tipo" value
 * @method eshopHome           setVigenciaDesde()       Sets the current record's "vigencia_desde" value
 * @method eshopHome           setVigenciaHasta()       Sets the current record's "vigencia_hasta" value
 * @method eshopHome           setOrden()               Sets the current record's "orden" value
 * @method eshopHome           setActivo()              Sets the current record's "activo" value
 * @method eshopHome           setTexto()               Sets the current record's "texto" value
 * @method eshopHome           setEshop()               Sets the current record's "eshop" value
 * @method eshopHome           setEshopHomeMultimedia() Sets the current record's "eshopHomeMultimedia" collection
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseeshopHome extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eshop_home');
        $this->hasColumn('id_eshop_home', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('denominacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'char', 5, array(
             'type' => 'char',
             'length' => 5,
             ));
        $this->hasColumn('vigencia_desde', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('vigencia_hasta', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('orden', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('eshop', array(
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'owningSide' => true));

        $this->hasMany('eshopHomeMultimedia', array(
             'local' => 'id_eshop_home',
             'foreign' => 'id_eshop_home'));
    }
}