<?php

/**
 * BaseproductoCategoriaEshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_producto_categoria
 * @property integer $id_eshop
 * @property char $tipo_prenda
 * @property integer $orden
 * @property productoCategoria $productoCategoria
 * @property eshop $eshop
 * 
 * @method integer                getIdProductoCategoria()   Returns the current record's "id_producto_categoria" value
 * @method integer                getIdEshop()               Returns the current record's "id_eshop" value
 * @method char                   getTipoPrenda()            Returns the current record's "tipo_prenda" value
 * @method integer                getOrden()                 Returns the current record's "orden" value
 * @method productoCategoria      getProductoCategoria()     Returns the current record's "productoCategoria" value
 * @method eshop                  getEshop()                 Returns the current record's "eshop" value
 * @method productoCategoriaEshop setIdProductoCategoria()   Sets the current record's "id_producto_categoria" value
 * @method productoCategoriaEshop setIdEshop()               Sets the current record's "id_eshop" value
 * @method productoCategoriaEshop setTipoPrenda()            Sets the current record's "tipo_prenda" value
 * @method productoCategoriaEshop setOrden()                 Sets the current record's "orden" value
 * @method productoCategoriaEshop setProductoCategoria()     Sets the current record's "productoCategoria" value
 * @method productoCategoriaEshop setEshop()                 Sets the current record's "eshop" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseproductoCategoriaEshop extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_categoria_eshop');
        $this->hasColumn('id_producto_categoria', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_eshop', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('tipo_prenda', 'char', 5, array(
             'type' => 'char',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('orden', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('productoCategoria', array(
             'local' => 'id_producto_categoria',
             'foreign' => 'id_producto_categoria',
             'owningSide' => true));

        $this->hasOne('eshop', array(
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'owningSide' => true));
    }
}