<?php

/**
 * BasereporteVentasPeriodo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property decimal $total_dinero_ingresado_flash
 * @property decimal $total_dinero_ingresado_permanente
 * @property decimal $total_dinero_ingresado_mixto
 * @property decimal $venta_total_flash
 * @property decimal $venta_total_permanente
 * @property decimal $costo_mercaderia_flash
 * @property decimal $costo_mercaderia_permanente
 * @property decimal $costo_envio_flash
 * @property decimal $costo_envio_permanente
 * @property decimal $costo_envio_mixto
 * @property decimal $comisiones_flash
 * @property decimal $comisiones_permanente
 * @property decimal $comisiones_mixto
 * @property integer $cantidad_pedidos_flash
 * @property integer $cantidad_pedidos_permanente
 * @property integer $cantidad_pedidos_mixto
 * @property integer $unidades_flash
 * @property integer $unidades_permanente
 * @property decimal $descuentos_usados_flash
 * @property decimal $descuentos_usados_permanente
 * @property decimal $descuentos_usados_mixto
 * @property decimal $bonificaciones_usados_flash
 * @property decimal $bonificaciones_usados_permanente
 * @property decimal $bonificaciones_usados_mixto
 * @property integer $cantidad_pedidos_0_50
 * @property integer $cantidad_pedidos_50_100
 * @property integer $cantidad_pedidos_100_200
 * @property integer $cantidad_pedidos_200_mas
 * @property integer $cliente_primera_compra
 * 
 * @method date                 getFecha()                             Returns the current record's "fecha" value
 * @method decimal              getTotalDineroIngresadoFlash()         Returns the current record's "total_dinero_ingresado_flash" value
 * @method decimal              getTotalDineroIngresadoPermanente()    Returns the current record's "total_dinero_ingresado_permanente" value
 * @method decimal              getTotalDineroIngresadoMixto()         Returns the current record's "total_dinero_ingresado_mixto" value
 * @method decimal              getVentaTotalFlash()                   Returns the current record's "venta_total_flash" value
 * @method decimal              getVentaTotalPermanente()              Returns the current record's "venta_total_permanente" value
 * @method decimal              getCostoMercaderiaFlash()              Returns the current record's "costo_mercaderia_flash" value
 * @method decimal              getCostoMercaderiaPermanente()         Returns the current record's "costo_mercaderia_permanente" value
 * @method decimal              getCostoEnvioFlash()                   Returns the current record's "costo_envio_flash" value
 * @method decimal              getCostoEnvioPermanente()              Returns the current record's "costo_envio_permanente" value
 * @method decimal              getCostoEnvioMixto()                   Returns the current record's "costo_envio_mixto" value
 * @method decimal              getComisionesFlash()                   Returns the current record's "comisiones_flash" value
 * @method decimal              getComisionesPermanente()              Returns the current record's "comisiones_permanente" value
 * @method decimal              getComisionesMixto()                   Returns the current record's "comisiones_mixto" value
 * @method integer              getCantidadPedidosFlash()              Returns the current record's "cantidad_pedidos_flash" value
 * @method integer              getCantidadPedidosPermanente()         Returns the current record's "cantidad_pedidos_permanente" value
 * @method integer              getCantidadPedidosMixto()              Returns the current record's "cantidad_pedidos_mixto" value
 * @method integer              getUnidadesFlash()                     Returns the current record's "unidades_flash" value
 * @method integer              getUnidadesPermanente()                Returns the current record's "unidades_permanente" value
 * @method decimal              getDescuentosUsadosFlash()             Returns the current record's "descuentos_usados_flash" value
 * @method decimal              getDescuentosUsadosPermanente()        Returns the current record's "descuentos_usados_permanente" value
 * @method decimal              getDescuentosUsadosMixto()             Returns the current record's "descuentos_usados_mixto" value
 * @method decimal              getBonificacionesUsadosFlash()         Returns the current record's "bonificaciones_usados_flash" value
 * @method decimal              getBonificacionesUsadosPermanente()    Returns the current record's "bonificaciones_usados_permanente" value
 * @method decimal              getBonificacionesUsadosMixto()         Returns the current record's "bonificaciones_usados_mixto" value
 * @method integer              getCantidadPedidos050()                Returns the current record's "cantidad_pedidos_0_50" value
 * @method integer              getCantidadPedidos50100()              Returns the current record's "cantidad_pedidos_50_100" value
 * @method integer              getCantidadPedidos100200()             Returns the current record's "cantidad_pedidos_100_200" value
 * @method integer              getCantidadPedidos200Mas()             Returns the current record's "cantidad_pedidos_200_mas" value
 * @method integer              getClientePrimeraCompra()              Returns the current record's "cliente_primera_compra" value
 * @method reporteVentasPeriodo setFecha()                             Sets the current record's "fecha" value
 * @method reporteVentasPeriodo setTotalDineroIngresadoFlash()         Sets the current record's "total_dinero_ingresado_flash" value
 * @method reporteVentasPeriodo setTotalDineroIngresadoPermanente()    Sets the current record's "total_dinero_ingresado_permanente" value
 * @method reporteVentasPeriodo setTotalDineroIngresadoMixto()         Sets the current record's "total_dinero_ingresado_mixto" value
 * @method reporteVentasPeriodo setVentaTotalFlash()                   Sets the current record's "venta_total_flash" value
 * @method reporteVentasPeriodo setVentaTotalPermanente()              Sets the current record's "venta_total_permanente" value
 * @method reporteVentasPeriodo setCostoMercaderiaFlash()              Sets the current record's "costo_mercaderia_flash" value
 * @method reporteVentasPeriodo setCostoMercaderiaPermanente()         Sets the current record's "costo_mercaderia_permanente" value
 * @method reporteVentasPeriodo setCostoEnvioFlash()                   Sets the current record's "costo_envio_flash" value
 * @method reporteVentasPeriodo setCostoEnvioPermanente()              Sets the current record's "costo_envio_permanente" value
 * @method reporteVentasPeriodo setCostoEnvioMixto()                   Sets the current record's "costo_envio_mixto" value
 * @method reporteVentasPeriodo setComisionesFlash()                   Sets the current record's "comisiones_flash" value
 * @method reporteVentasPeriodo setComisionesPermanente()              Sets the current record's "comisiones_permanente" value
 * @method reporteVentasPeriodo setComisionesMixto()                   Sets the current record's "comisiones_mixto" value
 * @method reporteVentasPeriodo setCantidadPedidosFlash()              Sets the current record's "cantidad_pedidos_flash" value
 * @method reporteVentasPeriodo setCantidadPedidosPermanente()         Sets the current record's "cantidad_pedidos_permanente" value
 * @method reporteVentasPeriodo setCantidadPedidosMixto()              Sets the current record's "cantidad_pedidos_mixto" value
 * @method reporteVentasPeriodo setUnidadesFlash()                     Sets the current record's "unidades_flash" value
 * @method reporteVentasPeriodo setUnidadesPermanente()                Sets the current record's "unidades_permanente" value
 * @method reporteVentasPeriodo setDescuentosUsadosFlash()             Sets the current record's "descuentos_usados_flash" value
 * @method reporteVentasPeriodo setDescuentosUsadosPermanente()        Sets the current record's "descuentos_usados_permanente" value
 * @method reporteVentasPeriodo setDescuentosUsadosMixto()             Sets the current record's "descuentos_usados_mixto" value
 * @method reporteVentasPeriodo setBonificacionesUsadosFlash()         Sets the current record's "bonificaciones_usados_flash" value
 * @method reporteVentasPeriodo setBonificacionesUsadosPermanente()    Sets the current record's "bonificaciones_usados_permanente" value
 * @method reporteVentasPeriodo setBonificacionesUsadosMixto()         Sets the current record's "bonificaciones_usados_mixto" value
 * @method reporteVentasPeriodo setCantidadPedidos050()                Sets the current record's "cantidad_pedidos_0_50" value
 * @method reporteVentasPeriodo setCantidadPedidos50100()              Sets the current record's "cantidad_pedidos_50_100" value
 * @method reporteVentasPeriodo setCantidadPedidos100200()             Sets the current record's "cantidad_pedidos_100_200" value
 * @method reporteVentasPeriodo setCantidadPedidos200Mas()             Sets the current record's "cantidad_pedidos_200_mas" value
 * @method reporteVentasPeriodo setClientePrimeraCompra()              Sets the current record's "cliente_primera_compra" value
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasereporteVentasPeriodo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reporte_ventas_periodo');
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('total_dinero_ingresado_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('total_dinero_ingresado_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('total_dinero_ingresado_mixto', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('venta_total_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('venta_total_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('costo_mercaderia_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('costo_mercaderia_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('costo_envio_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('costo_envio_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('costo_envio_mixto', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('comisiones_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('comisiones_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('comisiones_mixto', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('cantidad_pedidos_flash', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cantidad_pedidos_permanente', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cantidad_pedidos_mixto', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('unidades_flash', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('unidades_permanente', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('descuentos_usados_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('descuentos_usados_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('descuentos_usados_mixto', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('bonificaciones_usados_flash', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('bonificaciones_usados_permanente', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('bonificaciones_usados_mixto', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 9,
             ));
        $this->hasColumn('cantidad_pedidos_0_50', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cantidad_pedidos_50_100', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cantidad_pedidos_100_200', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cantidad_pedidos_200_mas', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cliente_primera_compra', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}