generator:
  class: sfDoctrineGenerator
  param:
    model_class:           faqCategoria
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          faq_categoria
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
      fields:
          id_faq_categoria: { label: Id }
          id_eshop: { label: eShop }
      list:
          title: Categorias de FAQs
          display: [id_faq_categoria, denominacion]
          max_per_page: 15
          object_actions:
            go_to_faqs:  { label: Gestión de Faqs }
            _edit:      ~
            _delete:    ~
      filter:
          display: [id_eshop]
      form:
          display: [id_faq_categoria, denominacion]
      edit:
          title: Editar Categoria de FAQ "%%denominacion%%" 
      new:
          title: Nuevar Categoria de FAQ