<?php

/**
 * bonificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class bonificacion extends Basebonificacion
{
	public function getFormateada()
	{
		$formateado = sprintf($this->getTipoDescuento()->getFormato(), $this->getValor() );
		return str_replace('.', ',', $formateado);
	}
	
	public function devolver()
	{
		$this->setFueUtilizada(false);
		$this->save();
	}
	
	public function utilizar()
	{
		$this->setFueUtilizada(true);
		$this->save();
	}	
	
	public function estaVencida()
	{	    
	    return $this->getDateTimeObject('vencimiento')->format("U") < time();
	}

	public function getPedidosAsociados()
	{	    
	    return pedidoTable::getInstance()->getByIdBonificacion( $this->getIdBonificacion() );
	}
	
	
}
