<?php

/**
 * carritoDescuento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class carritoDescuento extends BasecarritoDescuento
{
	public function getMonto($limitarMontoMaximo = false)
	{
		$montoProductos = sessionTable::getInstance()->getMontoProductos( $this->getIdSession() );
		
		$descuento = $this->getDescuento();
		
		$esFreeShipping = false;
		
		switch ($descuento->getIdTipoDescuento())
		{
			case tipoDescuento::FREESHIPPING:
	  			$carritoEnvio = carritoEnvioTable::getInstance()->getByIdSession( $this->getIdSession() );
	  			$montoDescuento = $carritoEnvio->getCosto(false);
	  			$esFreeShipping = true;
	  			break;
	  			
			case tipoDescuento::MONTOFIJO:
	  			$montoDescuento = $descuento->getValor(); 
	  			break;
	  			
			case tipoDescuento::PORCENTAJE:
	  			$montoDescuento = $montoProductos * ( $descuento->getValor() / 100 );
	  			break;
  			case tipoDescuento::COMPRA_MINIMA:
  			    $montoProductoMenorValor = carritoProductoItemTable::getInstance()->getMontoProductoMenorValor( $this->getIdSession() );
  			    $montoDescuento = $montoProductoMenorValor * ( $descuento->getValor() / 100 );
  			    break;
		}
		  		
  		if (!$esFreeShipping && $limitarMontoMaximo && $montoDescuento > $montoProductos)
  		{
  			$montoDescuento = $montoProductos;
  		}
  		
  		return $montoDescuento;
	}
	
    public function getArrayInfoAdicional()
    {
        if ( !$this->getInfoAdicional() ) return array();
        
        return json_decode( $this->getInfoAdicional(), true );
    }
}
