<?php

/**
 * categoriaMlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class categoriaMlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object categoriaMlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('categoriaMl');
    }
}