<?php

/**
 * devolucionProductoItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class devolucionProductoItem extends BasedevolucionProductoItem
{
    public function calcularMontoTotal()
    {
        $pedidoProductoItem = $this->getPedidoProductoItem();
        $devolucion = $this->getDevolucion();
        
        $valorProducto = $this->getCantidad() * $pedidoProductoItem->getPrecioDeluxe();
        
        $pedido = $pedidoProductoItem->getPedido();
        $pedidoDescuento =  pedidoDescuentoTable::getInstance()->getByIdPedido( $pedidoProductoItem->getIdPedido() );
        
        $montoDescuento = 0;
        if ( $pedidoDescuento && $pedidoDescuento->getIdTipoDescuento() != tipoDescuento::FREESHIPPING )
        {
            $montoDescuento = $valorProducto * ($pedido->getMontoDescuento() / $pedido->getMontoProductos() );
        }
        
        $valor = $valorProducto - $montoDescuento;
        
        return $valor;
    }
}
