<?php

/**
 * eshopTiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class eshopTiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eshopTiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('eshopTienda');
    }
    
    /**
     * Retorna todas las tiendas de un eshop
     *
     * @param integer $idEshop
     *
     * @return Doctrine_Collection
     */
    public function listByIdEshop( $idEshop )
    {
        return $this->createQuery('est')
                    ->innerJoin('est.eshopTiendaTiendaCategorias esttc')
                    ->innerJoin('esttc.eshopTiendaCategoria estc')
                    ->addwhere('est.id_eshop = ?', $idEshop)
                    ->useResultCache(true, null, 'eshopTienda_' . cacheHelper::getInstance()->genKey("listByIdEshop_" . $idEshop) )
                    ->execute();
    }
    
}