<?php

/**
 * eshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class eshop extends Baseeshop
{
    CONST ESHOP_DELUXE = 'DELUXE';
    CONST BENITO = 1;
    CONST RIE = 2;
    CONST JANETWISE = 5;
    CONST FELIX = 9;
    CONST NAIMA = 10;
    
    public function __toString()
    {
        return ( $this->getIdEshop() ) ? $this->getDenominacion() : 'Deluxe Buys';
    }
    
    public function preSave($event)
    {
        $this->clearCache($event);
    }
        
    public function preDelete($event)
    {
        $this->clearCache($event);
    }
    
    public function clearCache($event)
    {
        cacheHelper::getInstance()->delete('eshop_getByDominio_' . $this->getDominio() );
        cacheHelper::getInstance()->delete('eshop_getById_' . $this->getIdEshop() );
    }    

    public function getImageFilename()
    {
        return $this->getIdEshop() . '.jpg';       
    }

    public function getHashResumenPedidos( $fecha )
    {
        $hash = array();
        $hash[] = 'd3luxe-Pr4Gm0Re-h4SH';
        $hash[] = $this->getIdEshop();
        $hash[] = $fecha;

        return sha1( implode('|', $hash) );
    }

    public function getDevolucionRestringidaData()
    {

        if ( $this->getDevolucionRestringidaCategorias() == null ) {

            return array(
                'ids'     => json_decode( sfConfig::get('app_categoriaDevolucionRestringida_ids'), true),
                'mensaje' => sfConfig::get('app_categoriaDevolucionRestringida_mensaje')
            );

        } else {

            return array(
                'ids'     => json_decode( $this->getDevolucionRestringidaCategorias(), true),
                'mensaje' => $this->getDevolucionRestringidaMensaje()
            );

        }
    }

    public function getUsaLookbook()
    {
        return $this->getLookbook() != eshopLookbook::NO_USA;
    }
}
