<?php

/**
 * eshopLookbookProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class eshopLookbookProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eshopLookbookProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('eshopLookbookProducto');
    }

    /**
     * Retorna un listado de eshopLookbookProducto asociados a un $idEshopLookbook
     *
     * @param integer $idEshopLookbook
     *
     * @return Doctrine_Collection
     */
    public function listByIdEshopLookbook($idEshopLookbook)
    {
        return $this->createQuery('elp')
			        ->select('elp.*')
			        ->addwhere('elp.id_eshop_lookbook = ?', $idEshopLookbook)
			        ->execute();
    }

    /**
    * Retorna un objeto eshopLookbookProducto para ser eliminado 
    * 
    * @param number $idEshopLookbook
    * @param number $idProducto
    * 
    * @return eshopLookbookProducto
    */
    public function getOne($idEshopLookbook, $idProducto)
    {    
        return $this->createQuery('elp')
                    ->addwhere('elp.id_eshop_lookbook = ?', $idEshopLookbook)
                    ->addwhere('elp.id_producto = ?', $idProducto)  
                    ->fetchOne();
    }
}