<?php

/**
 * eshopHomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class eshopHomeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eshopHomeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('eshopHome');
    }

    /**
     * Retorna el listado ordenado para armar la home
     *
     * @param integer $idEshop
     *
     * @return Doctrine_Collection
     */
    public function listHome($idEshop)
    {
        $data = $this->createQuery('eh')
                     ->addWhere('eh.id_eshop = ?', $idEshop)
                     ->addWhere('eh.activo = ?', true)
                     ->orderBy('eh.orden DESC')
                     ->useResultCache(true, 3600, cacheHelper::getInstance()->genKey("eshopHome_listHome_" . $idEshop) )
                     ->execute();

        $eshopHomes = array();
        foreach ($data as $eshopHome) {
            if ( strtotime( $eshopHome->getVigenciaDesde() ) > time() ) continue;
            if ( strtotime( $eshopHome->getVigenciaHasta() ) < time() ) continue;
            $eshopHomes[] = $eshopHome;
        }

        return $eshopHomes;
    }

    /**
     * Retorna el eshopHome con orden mas bajo
     *
     * @param integer $idEshop
     *
     * @return eshopHome
     */
    public function getFirst($idEshop)
    {
        return $this->createQuery('eh')
                    ->addWhere('eh.id_eshop = ?', $idEshop)
                    ->orderBy('eh.orden ASC')
                    ->limit(1)
                    ->fetchOne();
    }
    
    /**
     * Retorna el eshopHome con orden mas alto
     *
     * @param integer $idEshop
     *
     * @return eshopHome
     */
    public function getLast($idEshop)
    {
        return $this->createQuery('eh')
                    ->addWhere('eh.id_eshop = ?', $idEshop)
                    ->orderBy('eh.orden DESC')
                    ->limit(1)
                    ->fetchOne();
    }
    
    /**
     * Retorna el anterior eshopHome para un $orden
     *
     * @param integer $idEshop
     * @param integer $orden
     *
     * @return eshopHome
     */
    public function getPrev( $idEshop, $orden )
    {
        return $this->createQuery('eh')
                    ->addWhere('eh.id_eshop = ?', $idEshop)
                    ->addWhere('eh.orden < ?', array( $orden ) )
                    ->orderBy('eh.orden DESC')
                    ->limit(1)
                    ->fetchOne();
    }
    
    /**
     * Retorna el siguiente eshopHome para un $orden
     *
     * @param integer $idEshop
     * @param integer $orden
     *
     * @return eshopHome
     */
    public function getNext( $idEshop, $orden )
    {
        return $this->createQuery('eh')
                    ->addWhere('eh.id_eshop = ?', $idEshop)
                    ->addWhere('eh.orden > ?', array( $orden ) )
                    ->orderBy('eh.orden ASC')
                    ->limit(1)
                    ->fetchOne();
    }
}