<?php

/**
 * eshopTiendaTiendaCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class eshopTiendaTiendaCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eshopTiendaTiendaCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('eshopTiendaTiendaCategoria');
    }
    
    /**
     * Retorna la eshopTiendaTiendaCategoria que coincide con la clave compuesta
     *
     * @param integer $idEshopTienda
     * @param integer $idEshopTiendaCategoria
     *
     * @return campanaMarca
     */
    public function getByCompoundKey( $idEshopTienda, $idEshopTiendaCategoria )
    {
        return $this->createQuery('ettc')
        ->addWhere('ettc.id_eshop_tienda = ?', array( $idEshopTienda ) )
        ->addWhere('ettc.id_eshop_tienda_categoria = ?', array( $idEshopTiendaCategoria ) )
        ->fetchOne();
    }
    
    /**
     * Retorna un listado de eshopTiendaTiendaCategoria a partir de $idEshopTienda
     *
     * @param integer $idEshopTienda
     *
     * @return eshopTiendaTiendaCategoria
     */
    public function listByIdEshopTienda( $idEshopTienda )
    {
        return $this->createQuery('ettc')
                    ->addWhere('ettc.id_eshop_tienda = ?', array( $idEshopTienda ) )
                    ->execute();
    }
    
}