<?php

/**
 * eshopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class eshopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eshopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('eshop');
    }
    
    /**
     * Retorna el listado total de eshops ordenado por denominacion
     *
     * @return Doctrine_Collection
     */
    public function listAll()
    {
        return $this->createQuery('e')
                    ->addWhere('e.activo = true')
                    ->orderBy('e.denominacion ASC')
                    ->execute();
    }
    
    /**
     * Retorna un eshop a partir de su dominio
     *
     * @param char $dominio
     *
     * @return eshop
     */
    public function getByDominio($dominio)
    {
        return $this->createQuery('e')
                    ->where('e.dominio  = ?', $dominio)
                    ->useResultCache(true, null, cacheHelper::getInstance()->genKey("eshop_getByDominio_" . $dominio) )
                    ->fetchOne();
    }
    
    /**
     * Retorna un eshop a partir de su idMarca
     *
     * @param int $idMarca
     *
     * @return eshop
     */
    public function getIdMarca($idMarca)
    {
        return $this->createQuery('e')
                    ->where('e.id_marca  = ?', $idMarca)
                    ->fetchOne();
    }

    /**
     * Retorna un eshop a partir de su $idEshop
     *
     * @param int $idEshop
     *
     * @return eshop
     */
    public function getById($idEshop)
    {
        return $this->createQuery('e')
        ->where('e.id_eshop  = ?', $idEshop)
        ->useResultCache(true, null, cacheHelper::getInstance()->genKey("eshop_getById_" . $idEshop) )
        ->fetchOne();
    }
    
    /**
     * Retorna el eshop para el dominio actual
     *
     * @return eshop
     */
    public function getCurrent()
    {
        $host = $_SERVER['HTTP_HOST'];
        $eshop = eshopTable::getInstance()->getByDominio( $host );

          if ( !$eshop && stripos($host, 'deluxebuys.' ) === false ) {
            echo 'eShop dado de baja';
            exit;
          }

      return $eshop;
    }
    
}