<?php

/**
 * eshopTiendaCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class eshopTiendaCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object eshopTiendaCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('eshopTiendaCategoria');
    }
    
    /**
     * Retorna todas las eshopTiendaCategoria
     *
     * @return Doctrine_Collection
     */
    public function listAll()
    {
        return $this->createQuery('tc')
        ->orderBy('tc.denominacion ASC')
        ->execute();
    }
}