<?php

/**
 * notificacionBackend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class notificacionBackend extends BasenotificacionBackend
{
    CONST TIPO_REPORTE_CRONOLOGICO                = 'CRONO';
    CONST TIPO_PRODUCTO_SET_CATEGORIA_ML          = 'PSCML';
    CONST TIPO_PRODUCTO_PUBLICAR_ML               = 'PPUML';
    CONST TIPO_PRODUCTO_EDITAR_STOCK              = 'PEDST';
    CONST TIPO_PRODUCTO_EDITAR_PRECIOS            = 'PEDPR';
    CONST TIPO_CAMPANA_ASIGNACION_CSV             = 'CACSV';
    CONST TIPO_PRODUCTO_EDICION_STOCK_PRECIO_CSV  = 'PECSV';
    CONST TIPO_PRODUCTO_SET_OUTLET                = 'PSOUT';
    CONST TIPO_PRODUCTO_SET_NO_OUTLET             = 'PNOUT';
    CONST TIPO_PRODUCTO_IMPORTAR                  = 'PIMPO';
    CONST TIPO_RESTAURAR_CAMPANA                  = 'RECAM';
    CONST TIPO_PREPARAR_ENVIO                     = 'PRENV';
    CONST TIPO_MENSAJE                            = 'MENSA';
    CONST TIPO_LIBRO_IVA_VENTAS                   = 'LIIVA';
    CONST TIPO_CITI_VENTAS                        = 'CIVEN';
    CONST TIPO_HOJA_DE_RUTA                       = 'HOJRU';
    
    protected $tipos = array(
        self::TIPO_REPORTE_CRONOLOGICO               => 'Reporte Cronologico',
        self::TIPO_PRODUCTO_SET_CATEGORIA_ML         => 'Productos - Set de Categoria de Mercado Libre',
        self::TIPO_PRODUCTO_PUBLICAR_ML              => 'Productos - Publicar en Mercado Libre',
        self::TIPO_PRODUCTO_EDITAR_STOCK             => 'Productos - Edición de Stocks',
        self::TIPO_PRODUCTO_EDITAR_PRECIOS           => 'Productos - Edición de Precios',
        self::TIPO_CAMPANA_ASIGNACION_CSV            => 'Campañas - Asignacion de productos, Precios y Stocks via CSV',
        self::TIPO_PRODUCTO_EDICION_STOCK_PRECIO_CSV => 'Productos - Edicion de Precios y Stocks via CSV',
        self::TIPO_PRODUCTO_SET_OUTLET               => 'Productos - Pasar a Outlet',
        self::TIPO_PRODUCTO_SET_NO_OUTLET            => 'Productos - Quitar a Outlet',
        self::TIPO_PRODUCTO_IMPORTAR                 => 'Productos - Importación',
        self::TIPO_RESTAURAR_CAMPANA                 => 'Campañas - Restauración',
        self::TIPO_PREPARAR_ENVIO                    => 'Pedidos - Preparar Envios',
        self::TIPO_MENSAJE                           => 'Mensaje informativo',
        self::TIPO_LIBRO_IVA_VENTAS                  => 'Facturacion - Libro IVA Ventas',
        self::TIPO_CITI_VENTAS                       => 'Facturacion - Citi Ventas',
        self::TIPO_HOJA_DE_RUTA                      => 'Logistica - Hoja de Ruta'
    );
    
    protected function getDenominacion()
    {
        return $this->tipos[ $this->getTipo() ];
    }
    
    protected function getResponseArray()
    {
        return json_decode( $this->getResponse(), true );
    }
    
}