<?php

/**
 * pagoNotificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class pagoNotificacion extends BasepagoNotificacion
{
	const ENVIADOMP = 'enviadoMP';
	const CRON = 'cron';
	const RETORNO = 'retorno';
	const MANUAL = 'manual';
	const INTERNO = 'interno';
	
	protected $responseArray;
	
	public function addMensaje( $mensaje )
	{
		$currentDate = date("d-M-Y H:i:s");
		
		$mensaje = $currentDate . ' - ' . $mensaje;
		
		if ( $this->getMensaje() )
		{
			$this->setMensaje( $this->getMensaje() . '<br/>' . $mensaje );
		}
		else 
		{
			$this->setMensaje( $mensaje );
		}
		$this->save();
	}
	
	public function getResponseArray()
	{
		if (!$this->responseArray)
		{
			$response = json_decode( $this->getResponse() );
			
			if ($response)
			{
				$this->responseArray = (array) $response;
			}
			else
			{
				$this->responseArray = false;
			}
						
		}				
		
		return $this->responseArray;
	}
	
}
