<?php

/**
 * premioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class premioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object premioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('premio');
    }
    
    /**
     * Retorna el listado de premios vigente para una fecha determinada
     *
     * @param string $fecha
     *
     * @return Doctrine_Collection
     */
    public function listVigentes($fecha)
    {
        return $this->createQuery('p')
        ->addWhere('date(p.fecha_desde) <= date(?) AND date(?) <= date(p.fecha_hasta)', array($fecha, $fecha))
        ->orderBy('p.monto_minimo desc')
        ->execute();
    }
    
}