<?php

/**
 * productoSticker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class productoSticker extends BaseproductoSticker
{
    public function __toString()
    {
        return $this->getDenominacion();
    }
    
    public function preSave($event)   {
        $this->clearCache($event);
    }
        
    public function preDelete($event) {
        @unlink( imageHelper::getInstance()->getPath('producto_sticker_chico', $this) );
        @unlink( imageHelper::getInstance()->getPath('producto_sticker_grande', $this) );
        
        $this->clearCache($event);        
    }
    
    public function clearCache($event)
    {
        cacheHelper::getInstance()->deleteByPrefix('productoSticker_listVigentes');
    }
        
    public function getImageFilename()
    {
        return $this->getIdProductoSticker() . '.png';
    }
}
