<?php

/**
 * productoCategoriaEshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class productoCategoriaEshop extends BaseproductoCategoriaEshop
{
	CONST TIPO_PRENDA_PRENDA  	 = 'PREND';
	CONST TIPO_PRENDA_ACCESORIO  = 'ACCES';
	
    public static $TIPOS_PRENDAS = array(
		self::TIPO_PRENDA_PRENDA  => 'Prendas',
        self::TIPO_PRENDA_ACCESORIO  => 'Accesorios'
    );

	public function preSave($event)   {	    
	    $this->clearCache($event);
	}
	
	public function preDelete($event) {
	    $this->clearCache($event);
	}
	
	public function clearCache($event)
	{
		cacheHelper::getInstance()->deleteByPrefix('productoCategoriaEshop');
	}

	public function getImageFilename()
	{
		return $this->getIdEshop() . '-' .  $this->getIdProductoCategoria() . '.jpg';		
	}

}
