<?php

/**
 * productoStickerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class productoStickerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object productoStickerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('productoSticker');
    }
    
    /**
     * Retorna el todos los stickers
     *
     * @return Doctrine_Collection
     */
    public function listAll()
    {
        return $this->createQuery('ps')
                    ->orderBy('ps.denominacion asc')
                    ->execute();
    }
    
    
    /**
     * Retorna el todos los stickers con productos activos
     *
     * @return Doctrine_Collection
     */
    public function listVigentes($idProductoGenero)
    {
        return $this->createQuery('ps')
                    ->select('ps.id_producto_sticker, ps.denominacion, ps.slug')
                    ->innerJoin('ps.producto p')
                    ->innerJoin('p.productoCategoria pc')
                    ->leftJoin('p.productoCampana pca')
                    ->leftJoin('pca.campana c')
                    ->addWhere('p.activo = true')
                    ->addWhere('pc.id_producto_genero = ?', $idProductoGenero)
                    ->addWhere('(c.id_campana is null) or (c.activo AND c.fecha_inicio < NOW() AND NOW() < c.fecha_fin and c.activo)')
                    ->orderBy('ps.denominacion asc')
                    ->useResultCache(true, null, cacheHelper::getInstance()->genKey("productoSticker_listVigentes_" . $idProductoGenero) )
                    ->execute();
    }
    
    
}