<?php

/**
 * productoTalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class productoTalle extends BaseproductoTalle
{
	
	public function __toString()
	{
		return $this->getDenominacion();
	}
	
	public function canOrderUp()
	{
		$first = productoTalleTable::getInstance()->getFirst();
		
		if ( $first )
		{
			return $first->getIdProductoTalle() != $this->getIdProductoTalle();
		}
		
		return false;
	}

	public function canOrderDown()
	{
		$last = productoTalleTable::getInstance()->getLast();
			
		if ( $last )
		{
			return $last->getIdProductoTalle() != $this->getIdProductoTalle();
		}
		
		return false;
	}
	
}
