<?php

/**
 * promoPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class promoPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object promoPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('promoPago');
    }


	/**
	* Retorna una promoPago a partir de su id
	* 
	* @param integer $idPromoPago
	* 
	* @return promoPago
	*/
    public function getById($idPromoPago)
    {
		return $this->createQuery('pp')
    			    ->where('pp.id_promo_pago  = ?', $idPromoPago)
    			    ->fetchOne();
    }

	/**
	 * Retorna la promoPago con orden mas bajo
	 *
	 * @return promoPago
	 */
	public function getFirst()
	{
	    return $this->createQuery('pp')
	    ->addWhere('pp.activo = true')
	    ->orderBy('pp.orden ASC')
	    ->limit(1)
	    ->fetchOne();
	}
	
	/**
	 * Retorna la promoPago con orden mas alto
	 *
	 * @return promoPago
	 */
	public function getLast()
	{
	    return $this->createQuery('pp')
	    ->addWhere('pp.activo = true')
	    ->orderBy('pp.orden DESC')
	    ->limit(1)
	    ->fetchOne();
	}
	
	/**
	 * Retorna la anterior promoPago en para un $orden
	 *
	 * @param integer $orden
	 *
	 * @return promoPago
	 */
	public function getPrev( $orden )
	{
	    return $this->createQuery('pp')
	    ->addWhere('pp.activo = true')
	    ->addWhere('pp.orden < ?', array( $orden ) )
	    ->orderBy('pp.orden DESC')
	    ->limit(1)
	    ->fetchOne();
	}
	
	/**
	 * Retorna la promoPago contenido en para un $orden
	 *
	 * @param integer $orden
	 *
	 * @return promoPago
	 */
	public function getNext( $orden )
	{
	    return $this->createQuery('pp')
	    ->addWhere('pp.activo = true')
	    ->addwhere('pp.orden > ?', array( $orden ) )
	    ->orderBy('pp.orden ASC')
	    ->limit(1)
	    ->fetchOne();
	}

	/**
	 * Retorna el listado de promoPago vigentes, para mostrar en frontend
	 *
	 * @param integer $idEshop
	 *
	 * @return Doctrine_Collection
	 */
	public function listVigentes( $idEshop )
	{
	    $q = $this->createQuery('pp');

	    if ( $idEshop ) {
    		$q->addWhere('pp.id_eshop = ?', $idEshop);
	    } else {
	    	$q->addWhere('pp.id_eshop IS NULL');
	    }

	    $q->addWhere('pp.vigencia_desde < NOW() AND NOW() < pp.vigencia_hasta')
	      ->addWhere('pp.activo = true')
	      ->addWhere('(pp.dias_semana IS NULL OR LOCATE( DAYOFWEEK(NOW()), pp.dias_semana ) >= 1 )')
	      ->orderBy('pp.orden DESC');

	    return $q->execute();
	}

	/**
	 * Retorna el listado de todas las promoPago, para mostrar en frontend en modo de prueba
	 *
	 * @param integer $idEshop
	 *
	 * @return Doctrine_Collection
	 */
	public function listAll( $idEshop )
	{
	    $q = $this->createQuery('pp');

	    if ( $idEshop ) {
    		$q->addWhere('pp.id_eshop = ?', $idEshop);
	    } else {
	    	$q->addWhere('pp.id_eshop IS NULL');
	    }

	    $q->orderBy('pp.orden DESC');

	    return $q->execute();
	}
}