<?php

/**
 * reciboEshopPedidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class reciboEshopPedidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object reciboEshopPedidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('reciboEshopPedido');
    }
}