<?php

/**
 * remito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class remito extends Baseremito
{
	public function getPedidos()
	{
		return pedidoTable::getInstance()->listbyIdRemito( $this->getIdRemito() );
	}
	
	public function getIdFormateado()
	{
		return sprintf('%05d', $this->getIdRemito() );
	}	
}
