<?php

/**
 * reporteCronologico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class reporteCronologico extends BasereporteCronologico
{
    CONST PEDIDO           = 'PEDID';
    CONST DEVOLUCION       = 'DEVOL';
    CONST FALTANTE         = 'FALTAN';
    CONST BAJA_FUERA_PLAZO = 'BAJAFP';
}
