<?php

/**
 * stockTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    deluxebuys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class stockTipo extends BasestockTipo
{
    CONST MANUAL_CARGA_INICIAL = 1;
    CONST MANUAL_REAJUSTE      = 2;
    CONST MANUAL_RESETEO       = 3;
    CONST MANUAL_REPOSICION    = 4;
    CONST MANUAL_OTRO          = 5;    
    
    CONST SISTEMA_CARGA_MASIVA          = 6;
    CONST SISTEMA_IMPORTACION_INICIAL   = 7;
    CONST SISTEMA_DEVOLUCION            = 8;
    CONST SISTEMA_BAJA_PEDIDO           = 9;
    CONST SISTEMA_VENTA                 = 10;
    CONST SISTEMA_FALTANTE              = 11;
    CONST SISTEMA_RESETEO_CAMPANA       = 12;
    CONST SISTEMA_REACTIVACION_PEDIDO   = 13;
    CONST SISTEMA_RESTAURACION_CAMPANA  = 15;
    CONST SISTEMA_CARGA_DESDE_OCA       = 16;
    CONST SISTEMA_RETIRO_OCA            = 17;
    CONST SISTEMA_RESETEO_REFUERZO      = 18;
}
