<?php

/**
 * tipoBonificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tipoBonificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tipoBonificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tipoBonificacion');
    }
}