# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    Content-Type: text/html; charset=utf-8
    Content-Language: es
    Cache-Control:  no-cache, no-store
    Pragma: no-cache
    Content-Style-Type: text/css
    imagetoolbar: no
    Expires: 0
    Last-Modified: 0

  metas:
    title: "Zapatos, Ropa y Accesorios - Tienda de Moda Online"
    description: "DeluxeBuys te brinda lo mejor en moda y tendencia con descuentos de hasta el 70%. Miles de vestidos, remeras, camisas, carteras, zapatos, accesorios y diseño para la mujer y el hombre. Descubrí lo último en ropa en internet"
    keywords: "deluxebuys, cartera, zapatos, ropa, mujer, camisas, blusas, remeras, moda, diseño, tendencia, club privado, benito fernandez, bikini, lenceria, descuento, shopping, pantalones, reef, rayban, vitamina, lupe, felix, rayban, uma, garcon garcia, natalia antolin, tossone, josefina ferroni, dolores iguacel, levis, nike, adidas, peuque, triumph, beleidades, dulce carola, admit one, punto uno, vestite y andate,  anne bonny, carla danelli, hawaianas, getien"

    SKYPE_TOOLBAR: SKYPE_TOOLBAR_PARSER_COMPATIBLE
    Author: ""
    Distribution: Global
    Robots: index,follow
    revisit-after: 1 month
    language: es
    DC.Creator: Pragmore.com
    google-site-verification: i7354Oq4Vslb59_nWS8FobnYgv-4iE5y4-ZUlW-q3Ik

  stylesheets:    [general.css, smoothness/jquery-ui-1.10.3.custom.min.css, malihu-custom-scrollbar-plugin-master/jquery.mCustomScrollbar.css]

  javascripts:    [lib/jquery-2.0.3.min.js, lib/jquery-ui-1.10.3.custom.min.js, lib/jquery.formatCurrency-1.4.0.min.js, lib/json2.js, lib/jquery.placeholder.min.js, lib/jquery.cookie.js, lib/jquery.mCustomScrollbar.concat.min.js, carritoRapido.js, helpers/generalHelper.js, general.js]
  
  has_layout:     true
  layout:         layout
