<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version270 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE orden_compra_oca SET estado = 'ENVIA';");
    }

    public function down()
    {
    }
}