<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version274 extends Doctrine_Migration_Base
{
    public function up()
    {        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("INSERT INTO ncredito_factura ( SELECT id_ncredito, id_factura FROM deluxebuys.ncredito );");
    }

    public function down()
    {
    }
}