<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version273 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ncredito_factura', array(
             'id_ncredito' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_factura' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_ncredito_has_factura_factura1' => 
              array(
              'fields' => 
              array(
               0 => 'id_factura',
              ),
              ),
              'fk_ncredito_has_factura_ncredito1' => 
              array(
              'fields' => 
              array(
               0 => 'id_ncredito',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_ncredito',
              1 => 'id_factura',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ncredito_factura');
    }
}