<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version281 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE pedido SET monto_facturacion = monto_total;");
    }

    public function down()
    {
    }
}