<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version283 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('producto_promo_permanente', 'pipi_12', array(
             'name' => 'pipi_12',
             'local' => 'id_promo_permanente',
             'foreign' => 'id_promo_permanente',
             'foreignTable' => 'promo_permanente',
             ));
        $this->createForeignKey('producto_promo_permanente', 'producto_promo_permanente_id_producto_producto_id_producto', array(
             'name' => 'producto_promo_permanente_id_producto_producto_id_producto',
             'local' => 'id_producto',
             'foreign' => 'id_producto',
             'foreignTable' => 'producto',
             ));
        $this->addIndex('producto_promo_permanente', 'producto_promo_permanente_id_promo_permanente', array(
             'fields' => 
             array(
              0 => 'id_promo_permanente',
             ),
             ));
        $this->addIndex('producto_promo_permanente', 'producto_promo_permanente_id_producto', array(
             'fields' => 
             array(
              0 => 'id_producto',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('producto_promo_permanente', 'pipi_12');
        $this->dropForeignKey('producto_promo_permanente', 'producto_promo_permanente_id_producto_producto_id_producto');
        $this->removeIndex('producto_promo_permanente', 'producto_promo_permanente_id_promo_permanente', array(
             'fields' => 
             array(
              0 => 'id_promo_permanente',
             ),
             ));
        $this->removeIndex('producto_promo_permanente', 'producto_promo_permanente_id_producto', array(
             'fields' => 
             array(
              0 => 'id_producto',
             ),
             ));
    }
}