<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version292 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('faltante', 'faltante_id_bonificacion_bonificacion_id_bonificacion', array(
             'name' => 'faltante_id_bonificacion_bonificacion_id_bonificacion',
             'local' => 'id_bonificacion',
             'foreign' => 'id_bonificacion',
             'foreignTable' => 'bonificacion',
             ));
        $this->addIndex('faltante', 'faltante_id_bonificacion', array(
             'fields' => 
             array(
              0 => 'id_bonificacion',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('faltante', 'faltante_id_bonificacion_bonificacion_id_bonificacion');
        $this->removeIndex('faltante', 'faltante_id_bonificacion', array(
             'fields' => 
             array(
              0 => 'id_bonificacion',
             ),
             ));
    }
}