<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version301 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('movimiento_stock_oca', 'movimiento_stock_oca_id_localidad_localidad_id_localidad', array(
             'name' => 'movimiento_stock_oca_id_localidad_localidad_id_localidad',
             'local' => 'id_localidad',
             'foreign' => 'id_localidad',
             'foreignTable' => 'localidad',
             ));
        $this->createForeignKey('movimiento_stock_oca_detalle', 'mipi', array(
             'name' => 'mipi',
             'local' => 'id_producto_item',
             'foreign' => 'id_producto_item',
             'foreignTable' => 'producto_item',
             ));
        $this->createForeignKey('movimiento_stock_oca_detalle', 'mimi_1', array(
             'name' => 'mimi_1',
             'local' => 'id_movimiento_stock_oca',
             'foreign' => 'id_movimiento_stock_oca',
             'foreignTable' => 'movimiento_stock_oca',
             ));
        $this->addIndex('movimiento_stock_oca', 'movimiento_stock_oca_id_localidad', array(
             'fields' => 
             array(
              0 => 'id_localidad',
             ),
             ));
        $this->addIndex('movimiento_stock_oca_detalle', 'movimiento_stock_oca_detalle_id_producto_item', array(
             'fields' => 
             array(
              0 => 'id_producto_item',
             ),
             ));
        $this->addIndex('movimiento_stock_oca_detalle', 'movimiento_stock_oca_detalle_id_movimiento_stock_oca', array(
             'fields' => 
             array(
              0 => 'id_movimiento_stock_oca',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('movimiento_stock_oca', 'movimiento_stock_oca_id_localidad_localidad_id_localidad');
        $this->dropForeignKey('movimiento_stock_oca_detalle', 'mipi');
        $this->dropForeignKey('movimiento_stock_oca_detalle', 'mimi_1');
        $this->removeIndex('movimiento_stock_oca', 'movimiento_stock_oca_id_localidad', array(
             'fields' => 
             array(
              0 => 'id_localidad',
             ),
             ));
        $this->removeIndex('movimiento_stock_oca_detalle', 'movimiento_stock_oca_detalle_id_producto_item', array(
             'fields' => 
             array(
              0 => 'id_producto_item',
             ),
             ));
        $this->removeIndex('movimiento_stock_oca_detalle', 'movimiento_stock_oca_detalle_id_movimiento_stock_oca', array(
             'fields' => 
             array(
              0 => 'id_movimiento_stock_oca',
             ),
             ));
    }
}