<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version304 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('oca_pedido_anulado', 'oca_pedido_anulado_id_pedido_pedido_id_pedido', array(
             'name' => 'oca_pedido_anulado_id_pedido_pedido_id_pedido',
             'local' => 'id_pedido',
             'foreign' => 'id_pedido',
             'foreignTable' => 'pedido',
             ));
        $this->addIndex('oca_pedido_anulado', 'oca_pedido_anulado_id_pedido', array(
             'fields' => 
             array(
              0 => 'id_pedido',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('oca_pedido_anulado', 'oca_pedido_anulado_id_pedido_pedido_id_pedido');
        $this->removeIndex('oca_pedido_anulado', 'oca_pedido_anulado_id_pedido', array(
             'fields' => 
             array(
              0 => 'id_pedido',
             ),
             ));
    }
}