<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version312 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('campana_stock_oca', array(
             'id_campana_stock_oca' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_producto_item' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'id_campana' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'cantidad' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_cso_producto_item' => 
              array(
              'fields' => 
              array(
               0 => 'id_producto_item',
              ),
              ),
              'fk_cso_campana' => 
              array(
              'fields' => 
              array(
               0 => 'id_campana',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_campana_stock_oca',
             ),
             ));
        $this->addColumn('orden_compra_oca', 'id_campana', 'integer', '4', array(
             ));
        $this->changeColumn('orden_compra_oca', 'estado', 'string', '5', array(
             'fixed' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('campana_stock_oca');
        $this->removeColumn('orden_compra_oca', 'id_campana');
    }
}