<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version322 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('banner_principal', 'denominacion', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('banner_principal', 'denominacion');
    }
}