<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version320 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('banner_principal', array(
             'id_banner_principal' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'activo' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'fecha_desde' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'fecha_hasta' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_banner_principal',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('banner_principal');
    }
}