<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version321 extends Doctrine_Migration_Base
{
    public function up()
    {
        $sfGuardPermission = new sfGuardPermission();
        $sfGuardPermission->setName('banners_principales');
        $sfGuardPermission->setDescription('Banners / Principales');
        $sfGuardPermission->save();
                
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE sf_guard_permission SET name = 'banners_secundarios', description = 'Banners / Secundarios' WHERE id = 35;");
    }
    
    public function down()
    {
    }
}