<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version325 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('faq_categoria', 'orden', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('faq_categoria', 'orden');
    }
}