<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version323 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('campana', 'permitir_pago_offline', 'boolean', '25', array(
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('campana', 'permitir_pago_offline');
    }
}