<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version335 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('campana', 'estimacion_envio_observacion');
    }

    public function down()
    {
        $this->addColumn('campana', 'estimacion_envio_observacion', 'clob', '65535', array(
             ));
    }
}