<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version345 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('post_comentario');
        $this->dropTable('post');
        $this->dropTable('post_categoria');
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("DELETE FROM sf_guard_permission WHERE id IN (44,45);");
    }

    public function down()
    {
        $this->createTable('post_comentario', array(
             'id_post_comentario' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_post' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'comentario' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'aprobado' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_post_comentario_post1' => 
              array(
              'fields' => 
              array(
               0 => 'id_post',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_post_comentario',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('post', array(
                'id_post' =>
                array(
                        'type' => 'integer',
                        'primary' => '1',
                        'autoincrement' => '1',
                        'length' => '4',
                ),
                'titulo' =>
                array(
                        'type' => 'string',
                        'length' => '255',
                ),
                'id_post_categoria' =>
                array(
                        'type' => 'integer',
                        'notnull' => '1',
                        'length' => '4',
                ),
                'fecha' =>
                array(
                        'notnull' => '1',
                        'type' => 'timestamp',
                        'length' => '25',
                ),
                'cuerpo' =>
                array(
                        'type' => 'clob',
                        'length' => '65535',
                ),
                'slug' =>
                array(
                        'type' => 'string',
                        'length' => '255',
                ),
        ), array(
                'type' => 'InnoDB',
                'indexes' =>
                array(
                        'fk_post_post_categoria1' =>
                        array(
                                'fields' =>
                                array(
                                        0 => 'id_post_categoria',
                                ),
                        ),
                        'ix_post_slug' =>
                        array(
                                'fields' =>
                                array(
                                        0 => 'slug',
                                ),
                        ),
                        'post_sluggable' =>
                        array(
                                'fields' =>
                                array(
                                        0 => 'slug',
                                ),
                                'type' => 'unique',
                        ),
                ),
                'primary' =>
                array(
                        0 => 'id_post',
                ),
                'collate' => '',
                'charset' => '',
        ));
        $this->createTable('post_categoria', array(
                'id_post_categoria' =>
                array(
                        'type' => 'integer',
                        'primary' => '1',
                        'autoincrement' => '1',
                        'length' => '4',
                ),
                'denominacion' =>
                array(
                        'type' => 'string',
                        'length' => '255',
                ),
                'slug' =>
                array(
                        'type' => 'string',
                        'length' => '255',
                ),
        ), array(
                'type' => 'InnoDB',
                'indexes' =>
                array(
                        'ix_postCategoria_slug' =>
                        array(
                                'fields' =>
                                array(
                                        0 => 'slug',
                                ),
                        ),
                        'post_categoria_sluggable' =>
                        array(
                                'fields' =>
                                array(
                                        0 => 'slug',
                                ),
                                'type' => 'unique',
                        ),
                ),
                'primary' =>
                array(
                        0 => 'id_post_categoria',
                ),
                'collate' => '',
                'charset' => '',
        ));
    }
}