<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version348 extends Doctrine_Migration_Base
{
    public function up()
    {   
        $configuracion = new configuracion();
        $configuracion->setIdConfiguracion('BHEAD');
        $configuracion->setDenominacion('Header / Banner');
        $configuracion->setValor(null);
        $configuracion->setTipo('IMAGE');
        $configuracion->save();
        
    }

    public function down()
    {
    }
}