<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version356 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('promo_permanente', 'destacar', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('promo_permanente', 'destacar');
    }
}