<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version368 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("DELETE FROM sf_guard_permission WHERE name='prod_y_campanas_forzar_ingresos_oca ';");
    }

    public function down()
    {
    }
}