<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version360 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('reporte_campana', array(
             'id_reporte_campana' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_campana' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'rubro' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'cantidad_pedidos' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'unidades_vendidas' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'unidades_promedio_pedido' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'total_facturado' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'pdb' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'costo_total' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'margen_bruto' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'margen_promedio' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'total_stock' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'ejecucion_de_stock' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'top_5_productos' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'ticket_promedio' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'objetivo_facturacion' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             'objetivo_resultado' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'length' => '1',
             ),
             'condicion_fiscal' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'cantidad_pedido_hombre' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'cantidad_pedido_mujer' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_reporte_campana_campana1' => 
              array(
              'fields' => 
              array(
               0 => 'id_campana',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_reporte_campana',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('reporte_campana');
    }
}