<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version369 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('devolucion', 'monto_total', 'decimal', '12', array(
             'scale' => '2',
             ));
    }

    public function down()
    {
        $this->removeColumn('devolucion', 'monto_total');
    }
}