<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version695 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('devuelto_marca', 'devuelto_marca_id_producto_item_producto_item_id_producto_item');
        $this->dropForeignKey('fallado', 'fallado_id_producto_item_producto_item_id_producto_item');

        $this->changeColumn('devuelto_marca', 'id_producto_item', 'integer', '4', array( 'notnull' => '1', ));
        $this->changeColumn('fallado', 'id_producto_item', 'integer', '4', array( 'notnull' => '1', ));

        $this->createForeignKey('devuelto_marca', 'devuelto_marca_id_producto_item_producto_item_id_producto_item', array(
             'name' => 'devuelto_marca_id_producto_item_producto_item_id_producto_item',
             'local' => 'id_producto_item',
             'foreign' => 'id_producto_item',
             'foreignTable' => 'producto_item',
             ));
        $this->createForeignKey('fallado', 'fallado_id_producto_item_producto_item_id_producto_item', array(
             'name' => 'fallado_id_producto_item_producto_item_id_producto_item',
             'local' => 'id_producto_item',
             'foreign' => 'id_producto_item',
             'foreignTable' => 'producto_item',
             ));

    }

    public function down()
    {        

    }
}