<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version697 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('session', 'session_id_usuario_usuario_id_usuario', array(
             'name' => 'session_id_usuario_usuario_id_usuario',
             'local' => 'id_usuario',
             'foreign' => 'id_usuario',
             'foreignTable' => 'usuario',
             ));
        $this->addIndex('session', 'session_id_usuario', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('session', 'session_id_usuario_usuario_id_usuario');
        $this->removeIndex('session', 'session_id_usuario', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
    }
}