<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version701 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'lookbook_titulo', 'string', '255', array(
             ));
        $this->addColumn('eshop', 'campaign_titulo', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'lookbook_titulo');
        $this->removeColumn('eshop', 'campaign_titulo');
    }
}