<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version706 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('devuelto_oca', 'fecha_retirado', 'timestamp', '25', array());
    }

    public function down()
    {
        $this->removeColumn('devuelto_oca', 'fecha_retirado');
    }
}