<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version713 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

        $q->execute("UPDATE eshop SET lista_sendgrid = '130302' WHERE id_eshop = 1;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '130304' WHERE id_eshop = 2;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '130308' WHERE id_eshop = 4;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '130306' WHERE id_eshop = 5;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '7040' WHERE id_eshop = 6;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '130311' WHERE id_eshop = 7;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '130310' WHERE id_eshop = 8;");
        $q->execute("UPDATE eshop SET lista_sendgrid = '130312' WHERE id_eshop = 9;");

    }

    public function down()
    {
    }
}