<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version717 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pedido', 'envio_destinatario', 'string', '60', array());
        $this->addColumn('pedido', 'envio_id_sucursal', 'integer', '4', array());
        $this->addColumn('pedido', 'envio_correo', 'string', '20', array());
        $this->addColumn('pedido', 'envio_servicio', 'char', '1', array());
    }

    public function down()
    {
    }
}