<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version709 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('producto_categoria_eshop', array(
             'id_producto_categoria' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_eshop' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'tipo_prenda' => 
             array(
              'type' => 'char',
              'notnull' => '1',
              'length' => '5',
             ),
             'orden' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '2',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_producto_categoria',
              1 => 'id_eshop',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('producto_categoria', 'tipo_prenda');
    }

    public function down()
    {
        $this->dropTable('producto_categoria_eshop');
        $this->addColumn('producto_categoria', 'tipo_prenda', 'char', '5', array(
             'notnull' => '1',
             'default' => 'PREND',
             ));
    }
}