<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version707 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE devuelto_oca SET fecha_retirado = fecha WHERE fue_retirado = true;");
    }

    public function down()
    {
    }
}