<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version730 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pedido', 'envio_id_pedido_envio_pack', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('pedido', 'envio_id_pedido_envio_pack');
    }
}