<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version727 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('carrito_envio', 'carrito_envio_id_provincia_provincia_id_provincia');
    }

    public function down()
    {
        $this->createForeignKey('carrito_envio', 'carrito_envio_id_provincia_provincia_id_provincia', array(
             'name' => 'carrito_envio_id_provincia_provincia_id_provincia',
             'local' => 'id_provincia',
             'foreign' => 'id_provincia',
             'foreignTable' => 'provincia',
             ));
    }
}