<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version722 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('pais');
        $this->removeColumn('provincia', 'id_pais');
        $this->removeColumn('usuario', 'id_pais');
    }

    public function down()
    {
    }
}