<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version725 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('carrito_envio', 'envio_servicio', 'char', '1', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('carrito_envio', 'envio_servicio');
    }
}