<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version731 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('devolucion', 'id_orden_retiro_oca');
        $this->addColumn('devolucion', 'envio_id_pedido_envio_pack', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('devolucion', 'id_orden_retiro_oca', 'string', '50', array(
             ));
        $this->removeColumn('devolucion', 'envio_id_pedido_envio_pack');
    }
}