<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version745 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

		$q->execute("UPDATE eshop SET lookbook_imagenes_fila = 3;");
        $q->execute("UPDATE eshop SET lookbook_imagenes_fila = 4 WHERE id_eshop = 6;");
        $q->execute("UPDATE eshop SET lookbook_imagenes_fila = 3 WHERE id_eshop = 7;");
        $q->execute("UPDATE eshop SET lookbook_imagenes_fila = 3 WHERE id_eshop = 8;");
        $q->execute("UPDATE eshop SET lookbook_imagenes_fila = 1 WHERE id_eshop = 9;");
    }

    public function down()
    {

    }
}