<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version751 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();

        $q->execute("UPDATE eshop SET tiendas_titulo = 'Tiendas';");
        $q->execute("UPDATE eshop SET tiendas_titulo = 'Locales' WHERE id_eshop = 10;");
    }

    public function down()
    {
    }
}