<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version750 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'tiendas_titulo', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'tiendas_titulo');
    }
}