<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version752 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'snapchat', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'snapchat');
    }
}