<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version757 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'texto_iniciar_sesion', 'string', '255', array(
             ));
        $this->addColumn('eshop', 'texto_seguinos', 'string', '255', array(
             ));
        $this->addColumn('eshop', 'texto_agregar_al_carro', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'texto_iniciar_sesion');
        $this->removeColumn('eshop', 'texto_seguinos');
        $this->removeColumn('eshop', 'texto_agregar_al_carro');
    }
}