<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version760 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'tiendas_subtitulo', 'string', '255', array(
             ));
        $this->addColumn('eshop', 'texto_carro_de_compras', 'string', '255', array(
             ));
        $this->addColumn('eshop', 'texto_soy_miembro', 'string', '255', array(
             ));
        $this->addColumn('eshop', 'texto_soy_nuevo', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'tiendas_subtitulo');
        $this->removeColumn('eshop', 'texto_carro_de_compras');
        $this->removeColumn('eshop', 'texto_soy_miembro');
        $this->removeColumn('eshop', 'texto_soy_nuevo');
    }
}