<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version761 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        $q->execute("UPDATE eshop SET tiendas_subtitulo = 'Nuestras Tiendas';");
        $q->execute("UPDATE eshop SET texto_carro_de_compras = 'CARRO DE COMPRAS';");
        $q->execute("UPDATE eshop SET texto_soy_miembro = 'Soy Miembro';");
        $q->execute("UPDATE eshop SET texto_soy_nuevo = 'Soy Nuevo';");

        $q->execute("UPDATE eshop SET tiendas_subtitulo = 'Nuestros Locales' WHERE id_eshop = 10;");
        $q->execute("UPDATE eshop SET texto_carro_de_compras = 'CART' WHERE id_eshop = 10;");
        $q->execute("UPDATE eshop SET texto_soy_miembro = 'MY ACCOUNT' WHERE id_eshop = 10;");
        $q->execute("UPDATE eshop SET texto_soy_nuevo = 'NEW MEMBER' WHERE id_eshop = 10;");
    }

    public function down()
    {
   
    }
}