<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version766 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        $q->execute("update reporte_cronologico rc set rc.cliente_tipo_documento = (select u.tipo_documento from pedido p inner join usuario u on u.id_usuario = p.id_usuario where rc.id_pedido = p.id_pedido) where rc.id_pedido is not null;");
        $q->execute("update reporte_cronologico rc set rc.cliente_documento = (select u.documento from pedido p inner join usuario u on u.id_usuario = p.id_usuario where rc.id_pedido = p.id_pedido) where rc.id_pedido is not null;");
        $q->execute("update reporte_cronologico rc set rc.cliente_email = (select u.email from pedido p inner join usuario u on u.id_usuario = p.id_usuario where rc.id_pedido = p.id_pedido) where rc.id_pedido is not null;");
    }

    public function down()
    {
    }
}