<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version777 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        



        $eshop = eshopTable::getInstance()->getById(10);
        $eshop->setTags( '<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KR3NLD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':
new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=
\'//www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,\'script\',\'dataLayer\',\'GTM-KR3NLD\');</script>
<!-- End Google Tag Manager -->
<script data-siteid="k49bXFdK" src="https://api.cartstack.com/js/customer-tracking/naima.com.ar_9309b7c4d0b016405cc862d93962042a.js" type="text/javascript">
</script>
' );
        $eshop->save();

        $eshop = eshopTable::getInstance()->getById(9);
        $eshop->setTags( '<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-53J6F3"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':
new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=
\'//www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,\'script\',\'dataLayer\',\'GTM-53J6F3\');</script>
<!-- End Google Tag Manager -->
' );
        $eshop->save();



       

    }

    public function down()
    {
    }
}