<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version775 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
		$q->execute("UPDATE eshop SET domicilio_comercial = 'Dr. Rómulo Naón 3433, CABA';");
		$q->execute("UPDATE eshop SET domicilio_comercial = 'Av. Alvear 1476 PB, CABA' WHERE id_eshop = 5;");
    }

    public function down()
    {
    }
}