<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version780 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('producto', 'codigo');
    }

    public function down()
    {
        $this->addColumn('producto', 'codigo', 'string', '30', array(
             ));
    }
}