<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('session_storage_backend', array(
             'id_session' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '255',
             ),
             'session_data' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'session_time' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_session',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('session_storage_frontend', array(
             'id_session' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '255',
             ),
             'session_data' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'session_time' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_session',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
    
        $this->dropTable('session_storage_backend');
        $this->dropTable('session_storage_frontend');
    }
}