<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('aviso_pedido', array(
             'id_aviso_pedido' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_tipo_aviso_pedido' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'fecha' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'id_pedido' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'hash' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'unique' => '1',
              'length' => '32',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_aviso_pedido_tipo_aviso_pedido1' => 
              array(
              'fields' => 
              array(
               0 => 'id_tipo_aviso_pedido',
              ),
              ),
              'fk_aviso_pedido_pedido1' => 
              array(
              'fields' => 
              array(
               0 => 'id_pedido',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_aviso_pedido',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('tipo_aviso_pedido', array(
             'id_tipo_aviso_pedido' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'primary' => '1',
              'length' => '5',
             ),
             'denominacion' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_tipo_aviso_pedido',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('aviso_pedido');
        $this->dropTable('tipo_aviso_pedido');
    }
}