<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('stock_historico', array(
             'id_stock_historico' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'fecha' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'cantidad' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'observacion' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'id_producto_item' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'id_stock' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_stock_historico_producto_item1' => 
              array(
              'fields' => 
              array(
               0 => 'id_producto_item',
              ),
              ),
              'fk_stock_historico_stock1' => 
              array(
              'fields' => 
              array(
               0 => 'id_stock',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_stock_historico',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('stock_historico');
    }
}