<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('factura', array(
             'id_factura' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_pedido' => 
             array(
              'type' => 'integer',
              'unique' => '1',
              'notnull' => '1',
              'length' => '4',
             ),
             'procesada' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cae' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'cae_vencimiento' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'comprobante' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'resultado' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'length' => '1',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_Factura_pedido1' => 
              array(
              'fields' => 
              array(
               0 => 'id_pedido',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_factura',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('factura_ws_request', array(
             'id_factura_ws_request' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'request' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'response' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_factura_ws_request',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('factura_ws_request_Factura', array(
             'id_factura_ws_request' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_factura' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_factura_ws_request_has_Factura_Factura1' => 
              array(
              'fields' => 
              array(
               0 => 'id_factura',
              ),
              ),
              'fk_factura_ws_request_has_Factura_factura_ws_request1' => 
              array(
              'fields' => 
              array(
               0 => 'id_factura_ws_request',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_factura_ws_request',
              1 => 'id_factura',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('factura');
        $this->dropTable('factura_ws_request');
        $this->dropTable('factura_ws_request_Factura');
    }
}