<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('factura', 'entorno', 'string', '4', array(
             'fixed' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('factura', 'entorno');
    }
}