<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version53 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('incidencia_factura_ncredito', 'resultado');
        $this->addColumn('incidencia_factura_ncredito', 'resuelta', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->addColumn('incidencia_factura_ncredito', 'resultado', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('incidencia_factura_ncredito', 'resuelta');
    }
}