<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ncredito', array(
             'id_ncredito' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_factura' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'procesada' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cae' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'cae_vencimiento' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'comprobante' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'resultado' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'length' => '1',
             ),
             'entorno' => 
             array(
              'type' => 'string',
              'fixed' => '1',
              'length' => '1',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_ncredito_Factura1' => 
              array(
              'fields' => 
              array(
               0 => 'id_factura',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_ncredito',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ncredito_ws_request', array(
             'id_ncredito_ws_request' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'request' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'response' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_ncredito_ws_request',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ncredito_ws_request_ncredito', array(
             'id_ncredito' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_ncredito_ws_request' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_ncredito_has_ncredito_ws_request_ncredito_ws_r1' => 
              array(
              'fields' => 
              array(
               0 => 'id_ncredito_ws_request',
              ),
              ),
              'fk_ncredito_has_ncredito_ws_request_ncredito1' => 
              array(
              'fields' => 
              array(
               0 => 'id_ncredito',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_ncredito',
              1 => 'id_ncredito_ws_request',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('ncredito');
        $this->dropTable('ncredito_ws_request');
        $this->dropTable('ncredito_ws_request_ncredito');
    }
}