<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('factura', 'unique_id_pedido_entorno', array(
             'fields' => 
             array(
              'id_pedido' => 
              array(
              'sorting' => 'ASC',
              ),
              'entorno' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('factura', 'unique_id_pedido_entorno', array(
             'fields' => 
             array(
              'id_pedido' => 
              array(
              'sorting' => 'ASC',
              ),
              'entorno' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
    }
}