<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version48 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ncredito', 'comprobante_factura', 'integer', '8', array(
             ));
        $this->changeColumn('factura', 'comprobante', 'integer', '8', array(
             ));
        $this->changeColumn('ncredito', 'comprobante', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('ncredito', 'comprobante_factura');
    }
}