<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('devolucion', array(
             'id_devolucion' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_producto_item' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'cantidad' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '45',
             ),
             'id_pedido' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'id_bonificacion' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_devolucion_producto_item1' => 
              array(
              'fields' => 
              array(
               0 => 'id_producto_item',
              ),
              ),
              'fk_devolucion_pedido1' => 
              array(
              'fields' => 
              array(
               0 => 'id_pedido',
              ),
              ),
              'fk_devolucion_bonificacion1' => 
              array(
              'fields' => 
              array(
               0 => 'id_bonificacion',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_devolucion',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('devolucion');
    }
}