<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('producto', 'es_oulet');
        $this->addColumn('producto', 'es_outlet', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->addColumn('producto', 'es_oulet', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('producto', 'es_outlet');
    }
}