<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version94 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('remito_pedido', 'remito_pedido_id_remito_remito_id_remito', array(
             'name' => 'remito_pedido_id_remito_remito_id_remito',
             'local' => 'id_remito',
             'foreign' => 'id_remito',
             'foreignTable' => 'remito',
             ));
        $this->createForeignKey('remito_pedido', 'remito_pedido_id_pedido_pedido_id_pedido', array(
             'name' => 'remito_pedido_id_pedido_pedido_id_pedido',
             'local' => 'id_pedido',
             'foreign' => 'id_pedido',
             'foreignTable' => 'pedido',
             ));
        $this->addIndex('remito_pedido', 'remito_pedido_id_remito', array(
             'fields' => 
             array(
              0 => 'id_remito',
             ),
             ));
        $this->addIndex('remito_pedido', 'remito_pedido_id_pedido', array(
             'fields' => 
             array(
              0 => 'id_pedido',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('remito_pedido', 'remito_pedido_id_remito_remito_id_remito');
        $this->dropForeignKey('remito_pedido', 'remito_pedido_id_pedido_pedido_id_pedido');
        $this->removeIndex('remito_pedido', 'remito_pedido_id_remito', array(
             'fields' => 
             array(
              0 => 'id_remito',
             ),
             ));
        $this->removeIndex('remito_pedido', 'remito_pedido_id_pedido', array(
             'fields' => 
             array(
              0 => 'id_pedido',
             ),
             ));
    }
}