<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version95 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('pedido', 'id_orden_retiro_oca');
        $this->addColumn('remito', 'id_orden_retiro_oca', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->addColumn('pedido', 'id_orden_retiro_oca', 'string', '50', array(
             ));
        $this->removeColumn('remito', 'id_orden_retiro_oca');
    }
}