<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version101 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('devolucion', 'devolucion_id_usuario_usuario_id_usuario', array(
             'name' => 'devolucion_id_usuario_usuario_id_usuario',
             'local' => 'id_usuario',
             'foreign' => 'id_usuario',
             'foreignTable' => 'usuario',
             ));
        $this->addIndex('devolucion', 'devolucion_id_usuario', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
        $this->addIndex('devolucion', 'fk_devolucion_usuario1', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('devolucion', 'devolucion_id_usuario_usuario_id_usuario');
        $this->removeIndex('devolucion', 'devolucion_id_usuario', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
        $this->removeIndex('devolucion', 'fk_devolucion_usuario1', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
    }
}