<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version123 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('campana', 'campana_id_comercial_comercial_id_comercial', array(
             'name' => 'campana_id_comercial_comercial_id_comercial',
             'local' => 'id_comercial',
             'foreign' => 'id_comercial',
             'foreignTable' => 'comercial',
             ));
        $this->addIndex('campana', 'campana_id_comercial', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('campana', 'campana_id_comercial_comercial_id_comercial');
        $this->removeIndex('campana', 'campana_id_comercial', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
    }
}