<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version128 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('campana', 'ix_campana_slug', array(
             'fields' => 
             array(
              0 => 'slug',
             ),
             ));
        $this->createForeignKey('campana_marca', 'campana_marca_id_comercial_comercial_id_comercial', array(
             'name' => 'campana_marca_id_comercial_comercial_id_comercial',
             'local' => 'id_comercial',
             'foreign' => 'id_comercial',
             'foreignTable' => 'comercial',
             ));
        $this->addIndex('campana_marca', 'campana_marca_id_comercial', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
        $this->addIndex('campana_marca', 'fk_campana_marca_comercial1', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
    }

    public function down()
    {

        $this->addIndex('campana', 'ix_campana_slug', array(
             'fields' => 
             array(
              0 => 'slug',
             ),
             ));
        $this->dropForeignKey('campana_marca', 'campana_marca_id_comercial_comercial_id_comercial');
        $this->removeIndex('campana_marca', 'campana_marca_id_comercial', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
        $this->removeIndex('campana_marca', 'fk_campana_marca_comercial1', array(
             'fields' => 
             array(
              0 => 'id_comercial',
             ),
             ));
    }
}