<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version134 extends Doctrine_Migration_Base
{
    public function up()
    {
        $devolucionMotivo = new devolucionMotivo();
        $devolucionMotivo->setIdDevolucionMotivo('TALLE');
        $devolucionMotivo->setDenominacion('El talle que compré no era el adecuado');
        $devolucionMotivo->save();
        
        $devolucionMotivo = new devolucionMotivo();
        $devolucionMotivo->setIdDevolucionMotivo('FALLA');
        $devolucionMotivo->setDenominacion('El producto estaba fallado');
        $devolucionMotivo->save();
        
        $devolucionMotivo = new devolucionMotivo();
        $devolucionMotivo->setIdDevolucionMotivo('INCOR');
        $devolucionMotivo->setDenominacion('El producto que recibí era incorrecto');
        $devolucionMotivo->save();
        
        $devolucionMotivo = new devolucionMotivo();
        $devolucionMotivo->setIdDevolucionMotivo('OTROS');
        $devolucionMotivo->setDenominacion('Otros');
        $devolucionMotivo->save();
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE devolucion SET motivo_otro = motivo");
        
        $devoluciones = devolucionTable::getInstance()->findAll();
        foreach ($devoluciones as $devolucion)
        {
            if ($devolucion->getMotivoOtro() == 'El talle que compré no era el adecuado') {
                $devolucion->setIdDevolucionMotivo('TALLE');
                $devolucion->setMotivoOtro('');
            }
            else if ($devolucion->getMotivoOtro() == 'El producto estaba fallado') {
                $devolucion->setIdDevolucionMotivo('FALLA');
                $devolucion->setMotivoOtro('');
            }
            else if ($devolucion->getMotivoOtro() == 'El producto que recibí era incorrecto') {
                $devolucion->setIdDevolucionMotivo('INCOR');
                $devolucion->setMotivoOtro('');
            }
            else {
                $devolucion->setIdDevolucionMotivo('OTROS');
            }
            
            $devolucion->save();
        }
        
        $this->removeColumn('devolucion', 'motivo');
    }

    public function down()
    {
        $this->addColumn('devolucion', 'motivo', 'clob', '65535', array(
             ));
    }
}