<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version140 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('usuario', 'source', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('usuario', 'source');
    }
}