<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version177 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('reporte_cronologico', 'bonificacion_motivo', 'string', '255', array(
             ));
        $this->changeColumn('reporte_cronologico', 'bonificacion_submotivo', 'string', '255', array(
             ));
    }

    public function down()
    {

    }
}