<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version183 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('campana', 'total_stock', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('campana', 'total_stock');
    }
}