<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version184 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('fuera_de_plazo_baja', array(
             'id_fuera_de_plazo_baja' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_pedido' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'tipo_credito' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'id_bonificacion' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_fuera_de_plazo_baja_pedido1' => 
              array(
              'fields' => 
              array(
               0 => 'id_pedido',
              ),
              ),
              'fk_fuera_de_plazo_baja_bonificacion1' => 
              array(
              'fields' => 
              array(
               0 => 'id_bonificacion',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_fuera_de_plazo_baja',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('fuera_de_plazo_baja');
    }
}