<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version198 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('descuento', 'restriccion_productos');
        $this->removeColumn('descuento', 'monto_minimo');
        $this->removeColumn('descuento', 'monto_maximo');
    }

    public function down()
    {        
        $this->addColumn('descuento', 'restriccion_productos', 'string', '8', array(
                'fixed' => '1',
        ));
        $this->addColumn('descuento', 'monto_minimo', 'decimal', '12', array(
                'scale' => '2',
        ));
        $this->addColumn('descuento', 'monto_maximo', 'decimal', '12', array(
                'scale' => '2',
        ));
        
    }
}