<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version206 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('stock_historico', 'stock_historico_id_stock_tipo_stock_tipo_id_stock_tipo', array(
             'name' => 'stock_historico_id_stock_tipo_stock_tipo_id_stock_tipo',
             'local' => 'id_stock_tipo',
             'foreign' => 'id_stock_tipo',
             'foreignTable' => 'stock_tipo',
             ));
        $this->addIndex('stock_historico', 'stock_historico_id_stock_tipo', array(
             'fields' => 
             array(
              0 => 'id_stock_tipo',
             ),
             ));
        $this->addIndex('stock_historico', 'fk_stock_historico_stock_tipo1', array(
             'fields' => 
             array(
              0 => 'id_stock_tipo',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('stock_historico', 'stock_historico_id_stock_tipo_stock_tipo_id_stock_tipo');
        $this->removeIndex('stock_historico', 'stock_historico_id_stock_tipo', array(
             'fields' => 
             array(
              0 => 'id_stock_tipo',
             ),
             ));
        $this->removeIndex('stock_historico', 'fk_stock_historico_stock_tipo1', array(
             'fields' => 
             array(
              0 => 'id_stock_tipo',
             ),
             ));
    }
}