<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version205 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('stock_historico', 'id_stock_tipo', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('stock_historico', 'id_stock_tipo');
    }
}