<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version200 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('localidad', 'activa', 'boolean', '25', array(
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('localidad', 'activa');
    }
}