<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version201 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('producto_campana_finalizada', array(
             'id_producto' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_campana' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_producto_has_campana_campana1' => 
              array(
              'fields' => 
              array(
               0 => 'id_campana',
              ),
              ),
              'fk_producto_has_campana_producto1' => 
              array(
              'fields' => 
              array(
               0 => 'id_producto',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_producto',
              1 => 'id_campana',
             ),
             ));
        $this->createTable('stock_tipo', array(
             'id_stock_tipo' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'denominacion' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'es_de_sistema' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_stock_tipo',
             ),
             ));
        $this->addColumn('stock', 'id_stock_tipo', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->dropTable('producto_campana_finalizada');
        $this->dropTable('stock_tipo');
        $this->removeColumn('stock', 'id_stock_tipo');
    }
}