<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version216 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('talle_set_zona', 'id_talle_set_zona', 'integer', '4', array(
             'primary' => '1',
             'autoincrement' => '1',
             ));
    }

    public function down()
    {

    }
}