<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version212 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('talle_set', array(
             'id_talle_set' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'denominacion' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'id_marca' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_talle_set_marca1' => 
              array(
              'fields' => 
              array(
               0 => 'id_marca',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_talle_set',
             ),
             ));
        $this->createTable('talle_set_zona', array(
             'id_talle_set_zona' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '45',
             ),
             'id_talle_set' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'id_talle_zona' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'id_producto_talle' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'desde' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'hasta' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_talle_set_has_talle_zona_talle_zona1' => 
              array(
              'fields' => 
              array(
               0 => 'id_talle_zona',
              ),
              ),
              'fk_talle_set_has_talle_zona_talle_set1' => 
              array(
              'fields' => 
              array(
               0 => 'id_talle_set',
              ),
              ),
              'fk_talle_set_has_talle_zona_producto_talle1' => 
              array(
              'fields' => 
              array(
               0 => 'id_producto_talle',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_talle_set_zona',
             ),
             ));
        $this->createTable('talle_zona', array(
             'id_talle_zona' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'denominacion' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_talle_zona',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('talle_set');
        $this->dropTable('talle_set_zona');
        $this->dropTable('talle_zona');
    }
}