<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version213 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('talle_set', 'talle_set_id_marca_marca_id_marca', array(
             'name' => 'talle_set_id_marca_marca_id_marca',
             'local' => 'id_marca',
             'foreign' => 'id_marca',
             'foreignTable' => 'marca',
             ));
        $this->createForeignKey('talle_set_zona', 'talle_set_zona_id_talle_set_talle_set_id_talle_set', array(
             'name' => 'talle_set_zona_id_talle_set_talle_set_id_talle_set',
             'local' => 'id_talle_set',
             'foreign' => 'id_talle_set',
             'foreignTable' => 'talle_set',
             ));
        $this->createForeignKey('talle_set_zona', 'talle_set_zona_id_talle_zona_talle_zona_id_talle_zona', array(
             'name' => 'talle_set_zona_id_talle_zona_talle_zona_id_talle_zona',
             'local' => 'id_talle_zona',
             'foreign' => 'id_talle_zona',
             'foreignTable' => 'talle_zona',
             ));
        $this->createForeignKey('talle_set_zona', 'tipi_2', array(
             'name' => 'tipi_2',
             'local' => 'id_producto_talle',
             'foreign' => 'id_producto_talle',
             'foreignTable' => 'producto_talle',
             ));
        $this->addIndex('talle_set', 'talle_set_id_marca', array(
             'fields' => 
             array(
              0 => 'id_marca',
             ),
             ));
        $this->addIndex('talle_set_zona', 'talle_set_zona_id_talle_set', array(
             'fields' => 
             array(
              0 => 'id_talle_set',
             ),
             ));
        $this->addIndex('talle_set_zona', 'talle_set_zona_id_talle_zona', array(
             'fields' => 
             array(
              0 => 'id_talle_zona',
             ),
             ));
        $this->addIndex('talle_set_zona', 'talle_set_zona_id_producto_talle', array(
             'fields' => 
             array(
              0 => 'id_producto_talle',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('talle_set', 'talle_set_id_marca_marca_id_marca');
        $this->dropForeignKey('talle_set_zona', 'talle_set_zona_id_talle_set_talle_set_id_talle_set');
        $this->dropForeignKey('talle_set_zona', 'talle_set_zona_id_talle_zona_talle_zona_id_talle_zona');
        $this->dropForeignKey('talle_set_zona', 'tipi_2');
        $this->removeIndex('talle_set', 'talle_set_id_marca', array(
             'fields' => 
             array(
              0 => 'id_marca',
             ),
             ));
        $this->removeIndex('talle_set_zona', 'talle_set_zona_id_talle_set', array(
             'fields' => 
             array(
              0 => 'id_talle_set',
             ),
             ));
        $this->removeIndex('talle_set_zona', 'talle_set_zona_id_talle_zona', array(
             'fields' => 
             array(
              0 => 'id_talle_zona',
             ),
             ));
        $this->removeIndex('talle_set_zona', 'talle_set_zona_id_producto_talle', array(
             'fields' => 
             array(
              0 => 'id_producto_talle',
             ),
             ));
    }
}