<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version220 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('usuario_talle_zona', 'usuario_talle_zona_id_talle_zona_talle_zona_id_talle_zona', array(
             'name' => 'usuario_talle_zona_id_talle_zona_talle_zona_id_talle_zona',
             'local' => 'id_talle_zona',
             'foreign' => 'id_talle_zona',
             'foreignTable' => 'talle_zona',
             ));
        $this->createForeignKey('usuario_talle_zona', 'usuario_talle_zona_id_usuario_usuario_id_usuario', array(
             'name' => 'usuario_talle_zona_id_usuario_usuario_id_usuario',
             'local' => 'id_usuario',
             'foreign' => 'id_usuario',
             'foreignTable' => 'usuario',
             ));
        $this->addIndex('usuario_talle_zona', 'usuario_talle_zona_id_talle_zona', array(
             'fields' => 
             array(
              0 => 'id_talle_zona',
             ),
             ));
        $this->addIndex('usuario_talle_zona', 'usuario_talle_zona_id_usuario', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('usuario_talle_zona', 'usuario_talle_zona_id_talle_zona_talle_zona_id_talle_zona');
        $this->dropForeignKey('usuario_talle_zona', 'usuario_talle_zona_id_usuario_usuario_id_usuario');
        $this->removeIndex('usuario_talle_zona', 'usuario_talle_zona_id_talle_zona', array(
             'fields' => 
             array(
              0 => 'id_talle_zona',
             ),
             ));
        $this->removeIndex('usuario_talle_zona', 'usuario_talle_zona_id_usuario', array(
             'fields' => 
             array(
              0 => 'id_usuario',
             ),
             ));
    }
}