<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version234 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('orden_compra_oca_detalle', 'fk_oc_oca_detalle_id_producto_item', array(
             'name' => 'fk_oc_oca_detalle_id_producto_item',
             'local' => 'id_producto_item',
             'foreign' => 'id_producto_item',
             'foreignTable' => 'producto_item',
             ));
        $this->createForeignKey('orden_compra_oca_detalle', 'fk_oc_oca_detalle_id_orden_compra_oca', array(
             'name' => 'fk_oc_oca_detalle_id_orden_compra_oca',
             'local' => 'id_orden_compra_oca',
             'foreign' => 'id_orden_compra_oca',
             'foreignTable' => 'orden_compra_oca',
             ));
        $this->addIndex('orden_compra_oca_detalle', 'orden_compra_oca_detalle_id_producto_item', array(
             'fields' => 
             array(
              0 => 'id_producto_item',
             ),
             ));
        $this->addIndex('orden_compra_oca_detalle', 'oc_oca_detalle_id_orden_compra_oca', array(
             'fields' => 
             array(
              0 => 'id_orden_compra_oca',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('orden_compra_oca_detalle', 'fk_oc_oca_detalle_id_producto_item');
        $this->dropForeignKey('orden_compra_oca_detalle', 'fk_oc_oca_detalle_id_orden_compra_oca');
        $this->removeIndex('orden_compra_oca_detalle', 'orden_compra_oca_detalle_id_producto_item', array(
             'fields' => 
             array(
              0 => 'id_producto_item',
             ),
             ));
        $this->removeIndex('orden_compra_oca_detalle', 'oc_oca_detalle_id_orden_compra_oca', array(
             'fields' => 
             array(
              0 => 'id_orden_compra_oca',
             ),
             ));
    }
}