<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version235 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('codigo_postal', array(
             'valor' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'valor',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('codigo_postal');
    }
}