<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version227 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('familia_color', 'id_familia_color', 'integer', '4', array(
             'primary' => '1',
             'autoincrement' => '1',
             ));
    }

    public function down()
    {

    }
}