<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version246 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('campana', 'facebook_compartida', 'boolean', '1', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('campana', 'facebook_compartida');
    }
}