<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version245 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('devolucion_producto_item', 'esta_fallado', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('devolucion_producto_item', 'esta_fallado');
    }
}