<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version250 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('oca_envio_pedido_log', 'fecha', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('oca_envio_pedido_log', 'fecha');
    }
}