<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version255 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('codigo_postal', array(
             'id_codigo_postal' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'valor' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '8',
             ),
             'id_provincia' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_codigo_postal_provincia1' => 
              array(
              'fields' => 
              array(
               0 => 'id_provincia',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_codigo_postal',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('codigo_postal');
    }
}