<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version254 extends Doctrine_Migration_Base
{
	
    public function up()
    {
        $this->dropTable('codigo_postal');		
    }

    public function down()
    {

    }
}
