<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version258 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pedido_producto_item', 'origen', 'string', '6', array(
             'fixed' => '1',
             ));
        $this->addColumn('producto_item', 'stock_campana', 'integer', '4', array(
             ));
        $this->addColumn('producto_item', 'stock_permanente', 'integer', '4', array(
             ));
        $this->addColumn('stock', 'origen', 'string', '6', array(
             'fixed' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('pedido_producto_item', 'origen');
        $this->removeColumn('producto_item', 'stock_campana');
        $this->removeColumn('producto_item', 'stock_permanente');
        $this->removeColumn('stock', 'origen');
    }
}