 <?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version262 extends Doctrine_Migration_Base
{
    public function up()
    {
        
        $permiso = sfGuardPermissionTable::getInstance()->findOneById(21);
        $permiso->setName('Prod. y Campañas / Control de Stock (Solo Permanente)');
        $permiso->save();
    }

    public function down()
    {
        
    }
}