<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version259 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE pedido_producto_item SET origen = 'OUTLET' WHERE es_outlet AND cantidad = venta_outlet;");
        $q->execute("UPDATE pedido_producto_item PPI INNER JOIN pedido_producto_item_campana PPIC ON PPI.id_pedido_producto_item = PPIC.id_pedido_producto_item SET PPI.origen = 'OFERTA' WHERE PPI.origen is null");
        $q->execute("UPDATE pedido_producto_item PPI LEFT JOIN pedido_producto_item_campana PPIC ON PPI.id_pedido_producto_item = PPIC.id_pedido_producto_item SET PPI.origen = 'STKPER' WHERE PPIC.id_campana is null and origen is null");
        
        $q->execute("UPDATE stock SET origen = 'OUTLET' WHERE es_outlet;");
        $q->execute("UPDATE stock S INNER JOIN producto_item PI ON S.id_producto_item =  PI.id_producto_item INNER JOIN producto P ON PI.id_producto =  P.id_producto INNER JOIN producto_campana PC ON PC.id_producto =  P.id_producto SET origen = 'OFERTA' WHERE origen IS NULL;");        
        $q->execute("UPDATE stock S INNER JOIN producto_item PI ON S.id_producto_item =  PI.id_producto_item INNER JOIN producto P ON PI.id_producto =  P.id_producto LEFT JOIN producto_campana PC ON PC.id_producto =  P.id_producto SET origen = 'STKPER' WHERE origen IS NULL AND PC.id_campana IS NULL;");        
    }

    public function down()
    {

    }
}