<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version374 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $data = $q->fetchAll("
                                SELECT id_producto_item, sum(cantidad) FROM deluxebuys.stock
                                WHERE origen = 'OUTLET'
                                AND fecha <= '2013-12-31 23:59:59'
                                GROUP BY id_producto_item
                                HAVING sum(cantidad) > 0;
                             "
                             );
        
        foreach( $data as $row )
        {   
            $stock = new stock();
            $stock->setCantidad( $row['sum(cantidad)'] * -1 );
            $stock->setIdProductoItem( $row['id_producto_item'] );
            $stock->setFecha('2013-12-31 23:59:59');
            $stock->setObservacion('Ajuste');
            $stock->setEmpaquetado(0);
            $stock->setIdStockTipo( stockTipo::MANUAL_REAJUSTE );
            $stock->setOrigen( producto::ORIGEN_OUTLET );
            $stock->save();
            
            $productoItem = productoItemTable::getInstance()->findOneByIdProductoItem( $row['id_producto_item'] );
            $productoItem->updateStock();
        }    
    }

    public function down()
    {
        
    }
}