<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version381 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE premio SET tipo_premio = 'MFIJO';");
    }

    public function down()
    {
        $this->removeColumn('premio', 'tipo_premio');
    }
}