<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version388 extends Doctrine_Migration_Base
{
    public function up()
    {
        $configuracion = new configuracion();
        $configuracion->setIdConfiguracion('CAPHV');
        $configuracion->setDenominacion('Carrito / Pago HCBC con Visa');
        $configuracion->setValor(null);
        $configuracion->setTipo('IMAGE');
        $configuracion->save();
        
        $configuracion = new configuracion();
        $configuracion->setIdConfiguracion('CAPHA');
        $configuracion->setDenominacion('Carrito / Pago HCBC con American Express');
        $configuracion->setValor(null);
        $configuracion->setTipo('IMAGE');
        $configuracion->save();
        
    }

    public function down()
    {
    }
}