<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version393 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('fallado', 'descripcion', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('fallado', 'descripcion');
    }
}