<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version397 extends Doctrine_Migration_Base
{
    public function up()
    {
        $permiso = new sfGuardPermission();
        $permiso->setName('prod_y_campanas_stickers');
        $permiso->setDescription('Prod. y Campañas / Stickers');
        $permiso->save();
        
        $productoSticker = new productoSticker();
        $productoSticker->setDenominacion('Nuestro Elegido!');
        $productoSticker->save();
        $elegido = $productoSticker;
        
        $productoSticker = new productoSticker();
        $productoSticker->setDenominacion('Envio Gratis');
        $productoSticker->save();
        $envioGratis = $productoSticker;
        
        $productoSticker = new productoSticker();
        $productoSticker->setDenominacion('Envio en 48 hs');
        $productoSticker->save();
        $envio48 = $productoSticker;
        
        $productoSticker = new productoSticker();
        $productoSticker->setDenominacion('+Vendido');
        $productoSticker->save();
        $masVendido = $productoSticker;
        
        $productoSticker = new productoSticker();
        $productoSticker->setDenominacion('We Love');
        $productoSticker->save();
        $weLove = $productoSticker;
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE producto SET id_producto_sticker = " . $elegido->getIdProductoSticker() . " WHERE sticker = 'ELEGID';");
        $q->execute("UPDATE producto SET id_producto_sticker = " . $envioGratis->getIdProductoSticker() . " WHERE sticker = 'ENVGRA';");
        $q->execute("UPDATE producto SET id_producto_sticker = " . $envio48->getIdProductoSticker() . " WHERE sticker = 'ENVI48';");
        $q->execute("UPDATE producto SET id_producto_sticker = " . $masVendido->getIdProductoSticker() . " WHERE sticker = 'VENDID';");
        $q->execute("UPDATE producto SET id_producto_sticker = " . $weLove->getIdProductoSticker() . " WHERE sticker = 'WELOVE';");
        
    }

    public function down()
    {
    }
}