<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version409 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $result = $q->fetchAll("SELECT max(id_campana), id_marca FROM deluxebuys.campana_marca WHERE email_orden_compra IS NOT NULL AND email_orden_compra <> '' GROUP BY id_marca ORDER BY id_marca;");

        foreach ( $result as $row )
        {
            $idCampana = $row['max(id_campana)'];
            $idMarca = $row['id_marca'];
            
            $campanaMarca = campanaMarcaTable::getInstance()->getByCompoundKey($idCampana, $idMarca);
            $marca = marcaTable::getInstance()->getOneById($idMarca);
            
            $marca->setEmailComercial( $campanaMarca->getEmailOrdenCompra() );
            $marca->save();
            
        }
        
    }

    public function down()
    {
    }
}