<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version405 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('categoria_ml', array(
             'id_categoria_ml' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_categoria_ml_padre' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'denominacion' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'id_externo' => 
             array(
              'type' => 'string',
              'length' => '20',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_categoria_ml_id_categoria_ml_padre' => 
              array(
              'fields' => 
              array(
               0 => 'id_categoria_ml_padre',
              ),
              ),
              'id_categoria_ml_padre' => 
              array(
              'fields' => 
              array(
               0 => 'id_categoria_ml_padre',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_categoria_ml',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('categoria_ml');
    }
}