<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version404 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE producto_sticker SET slug='nuestro-elegido' WHERE id_producto_sticker='1';");
        $q->execute("UPDATE producto_sticker SET slug='envio-gratis' WHERE id_producto_sticker='2';");
        $q->execute("UPDATE producto_sticker SET slug='envio-en-48hs' WHERE id_producto_sticker='3';");
        $q->execute("UPDATE producto_sticker SET slug='mas-vendido' WHERE id_producto_sticker='4';");
        $q->execute("UPDATE producto_sticker SET slug='we-love' WHERE id_producto_sticker='5';");
        $q->execute("UPDATE producto_sticker SET denominacion='+Vendidos', slug='mas-vendidos' WHERE id_producto_sticker='4';");
        
    }

    public function down()
    {
    }
}