<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version412 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('publicacion_ml', 'publicacion_ml_id_producto_producto_id_producto', array(
             'name' => 'publicacion_ml_id_producto_producto_id_producto',
             'local' => 'id_producto',
             'foreign' => 'id_producto',
             'foreignTable' => 'producto',
             ));
        $this->addIndex('publicacion_ml', 'publicacion_ml_id_producto', array(
             'fields' => 
             array(
              0 => 'id_producto',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('publicacion_ml', 'publicacion_ml_id_producto_producto_id_producto');
        $this->removeIndex('publicacion_ml', 'publicacion_ml_id_producto', array(
             'fields' => 
             array(
              0 => 'id_producto',
             ),
             ));
    }
}