<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version422 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('codigo_postal', 'id_zona', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('codigo_postal', 'id_zona');
    }
}