<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version413 extends Doctrine_Migration_Base
{
    public function up()
    {
    	$this->addColumn('categoria_ml', 'attribute_types', 'string', '40', array(
    	));
    }

    public function down()
    {
        $this->removeColumn('categoria_ml', 'attribute_types');
    }
}