<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version420 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('carrito_envio', 'carrito_envio_id_localidad_localidad_id_localidad');
        $this->dropForeignKey('direccion_envio', 'direccion_envio_id_localidad_localidad_id_localidad');
        $this->dropForeignKey('pedido', 'pedido_envio_id_localidad_localidad_id_localidad');
        $this->removeIndex('carrito_envio', 'fk_carrito_envio_localidad1', array(
             'fields' => 
             array(
              0 => 'id_localidad',
             ),
             ));
        $this->removeIndex('direccion_envio', 'fk_direccion_envio_localidad1', array(
             'fields' => 
             array(
              0 => 'id_localidad',
             ),
             ));
        $this->removeIndex('pedido', 'fk_pedido_localidad1', array(
             'fields' => 
             array(
              0 => 'envio_id_localidad',
             ),
             ));
        $this->createForeignKey('carrito_envio', 'carrito_envio_id_provincia_provincia_id_provincia', array(
             'name' => 'carrito_envio_id_provincia_provincia_id_provincia',
             'local' => 'id_provincia',
             'foreign' => 'id_provincia',
             'foreignTable' => 'provincia',
             ));
        $this->createForeignKey('direccion_envio', 'direccion_envio_id_provincia_provincia_id_provincia', array(
             'name' => 'direccion_envio_id_provincia_provincia_id_provincia',
             'local' => 'id_provincia',
             'foreign' => 'id_provincia',
             'foreignTable' => 'provincia',
             ));
        $this->createForeignKey('pedido', 'pedido_id_provincia_provincia_id_provincia', array(
             'name' => 'pedido_id_provincia_provincia_id_provincia',
             'local' => 'envio_id_provincia',
             'foreign' => 'id_provincia',
             'foreignTable' => 'provincia',
             ));
        $this->addIndex('carrito_envio', 'fk_carrito_envio_id_provincia1', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->addIndex('direccion_envio', 'fk_direccion_envio_id_provincia1', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->addIndex('pedido', 'fk_pedido_provincia1', array(
             'fields' => 
             array(
              0 => 'envio_id_provincia',
             ),
             ));
        
        $this->dropForeignKey('devolucion', 'devolucion_id_localidad_localidad_id_localidad');
        $this->dropForeignKey('movimiento_stock_oca', 'movimiento_stock_oca_id_localidad_localidad_id_localidad');
        $this->removeIndex('devolucion', 'fk_devolucion_localidad1', array(
        		'fields' =>
        		array(
        				0 => 'id_localidad',
        		),
        ));
        $this->removeIndex('movimiento_stock_oca', 'fk_movimiento_stock_oca_localidad1', array(
        		'fields' =>
        		array(
        				0 => 'id_localidad',
        		),
        ));
        $this->createForeignKey('devolucion', 'devolucion_id_provincia_provincia_id_provincia', array(
        		'name' => 'devolucion_id_provincia_provincia_id_provincia',
        		'local' => 'id_provincia',
        		'foreign' => 'id_provincia',
        		'foreignTable' => 'provincia',
        ));
        $this->createForeignKey('movimiento_stock_oca', 'movimiento_stock_oca_id_provincia_provincia_id_provincia', array(
        		'name' => 'movimiento_stock_oca_id_provincia_provincia_id_provincia',
        		'local' => 'id_provincia',
        		'foreign' => 'id_provincia',
        		'foreignTable' => 'provincia',
        ));
        $this->addIndex('devolucion', 'devolucion_id_provincia', array(
        		'fields' =>
        		array(
        				0 => 'id_provincia',
        		),
        ));
        $this->addIndex('movimiento_stock_oca', 'movimiento_stock_oca_id_provincia', array(
        		'fields' =>
        		array(
        				0 => 'id_provincia',
        		),
        ));
    }

    public function down()
    {
        $this->createForeignKey('carrito_envio', 'carrito_envio_id_localidad_localidad_id_localidad', array(
             'name' => 'carrito_envio_id_localidad_localidad_id_localidad',
             'local' => 'id_localidad',
             'foreign' => 'id_localidad',
             'foreignTable' => 'localidad',
             ));
        $this->createForeignKey('direccion_envio', 'direccion_envio_id_localidad_localidad_id_localidad', array(
             'name' => 'direccion_envio_id_localidad_localidad_id_localidad',
             'local' => 'id_localidad',
             'foreign' => 'id_localidad',
             'foreignTable' => 'localidad',
             ));
        $this->createForeignKey('pedido', 'pedido_envio_id_localidad_localidad_id_localidad', array(
             'name' => 'pedido_envio_id_localidad_localidad_id_localidad',
             'local' => 'envio_id_localidad',
             'foreign' => 'id_localidad',
             'foreignTable' => 'localidad',
             ));
        $this->addIndex('carrito_envio', 'fk_carrito_envio_localidad1', array(
             'fields' => 
             array(
              0 => 'id_localidad',
             ),
             ));
        $this->addIndex('direccion_envio', 'fk_direccion_envio_localidad1', array(
             'fields' => 
             array(
              0 => 'id_localidad',
             ),
             ));
        $this->addIndex('localidad', 'fk_localidad_id_mercado_libre', array(
             'fields' => 
             array(
              0 => 'id_mercado_libre',
             ),
             ));
        $this->addIndex('pedido', 'fk_pedido_localidad1', array(
             'fields' => 
             array(
              0 => 'envio_id_localidad',
             ),
             ));
        $this->addIndex('provincia', 'fk_provincia_id_mercado_libre', array(
             'fields' => 
             array(
              0 => 'id_mercado_libre',
             ),
             ));
        $this->dropForeignKey('carrito_envio', 'carrito_envio_id_provincia_provincia_id_provincia');
        $this->dropForeignKey('direccion_envio', 'direccion_envio_id_provincia_provincia_id_provincia');
        $this->dropForeignKey('pedido', 'pedido_id_provincia_provincia_id_provincia');
        $this->removeIndex('carrito_envio', 'carrito_envio_id_provincia', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->removeIndex('carrito_envio', 'fk_carrito_envio_id_provincia1', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->removeIndex('direccion_envio', 'direccion_envio_id_provincia', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->removeIndex('direccion_envio', 'fk_direccion_envio_id_provincia1', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->removeIndex('pedido', 'pedido_id_provincia', array(
             'fields' => 
             array(
              0 => 'id_provincia',
             ),
             ));
        $this->removeIndex('pedido', 'fk_pedido_provincia1', array(
             'fields' => 
             array(
              0 => 'envio_id_provincia',
             ),
             ));
        
        $this->createForeignKey('devolucion', 'devolucion_id_localidad_localidad_id_localidad', array(
        		'name' => 'devolucion_id_localidad_localidad_id_localidad',
        		'local' => 'id_localidad',
        		'foreign' => 'id_localidad',
        		'foreignTable' => 'localidad',
        ));
        $this->createForeignKey('movimiento_stock_oca', 'movimiento_stock_oca_id_localidad_localidad_id_localidad', array(
        		'name' => 'movimiento_stock_oca_id_localidad_localidad_id_localidad',
        		'local' => 'id_localidad',
        		'foreign' => 'id_localidad',
        		'foreignTable' => 'localidad',
        ));
        $this->addIndex('devolucion', 'fk_devolucion_localidad1', array(
        		'fields' =>
        		array(
        				0 => 'id_localidad',
        		),
        ));
        $this->addIndex('movimiento_stock_oca', 'fk_movimiento_stock_oca_localidad1', array(
        		'fields' =>
        		array(
        				0 => 'id_localidad',
        		),
        ));
        $this->dropForeignKey('devolucion', 'devolucion_id_provincia_provincia_id_provincia');
        $this->dropForeignKey('movimiento_stock_oca', 'movimiento_stock_oca_id_provincia_provincia_id_provincia');
        $this->removeIndex('devolucion', 'devolucion_id_provincia', array(
        		'fields' =>
        		array(
        				0 => 'id_provincia',
        		),
        ));
        $this->removeIndex('movimiento_stock_oca', 'movimiento_stock_oca_id_provincia', array(
        		'fields' =>
        		array(
        				0 => 'id_provincia',
        		),
        ));
    }
}