<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version426 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('publicacion_ml', 'data_mercado_libre', 'clob', '65535', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('publicacion_ml', 'data_mercado_libre');
    }
}