<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version435 extends Doctrine_Migration_Base
{
    public function up()
    {
    	$q = Doctrine_Manager::getInstance()->getCurrentConnection();
    	$q->execute("ALTER TABLE reporte_cronologico ADD COLUMN tipo_envio CHAR(3) NULL DEFAULT NULL  AFTER costo_envio_deluxe;");
    	
    	$q->execute("UPDATE reporte_cronologico r SET tipo_envio = (SELECT envio_tipo FROM pedido p WHERE p.id_pedido = r.id_pedido);");
    	$q->execute("UPDATE reporte_cronologico r SET tipo_envio = NULL WHERE accion <> 'Pedido Total';");    	
    }

    public function down()
    {
    }
}