<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version437 extends Doctrine_Migration_Base
{
    public function up()
    {
    	$permiso = new sfGuardPermission();
    	$permiso->setName('reportes_adnetworks');
    	$permiso->setDescription('Reportes / Reporte de AdNetworks');
    	$permiso->save();
    }

    public function down()
    {
    }
}