<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version442 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('devuelto_marca', array(
             'id_devuelto_marca' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'id_pedido_producto_item' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'devuelto' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'fecha' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_devuelto_mmarca_ppi1' => 
              array(
              'fields' => 
              array(
               0 => 'id_pedido_producto_item',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_devuelto_marca',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('devuelto_marca');
    }
}