<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version447 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('devolucion_producto_item', 'cantidad_stock', 'integer', '4', array(
             'default' => '0',
             ));
        $this->changeColumn('devolucion_producto_item', 'cantidad_fallados', 'integer', '4', array(
             'default' => '0',
             ));
        $this->changeColumn('devolucion_producto_item', 'cantidad_devueltos_marcas', 'integer', '4', array(
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}