<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version453 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("UPDATE reporte_cronologico SET accion = 'Bonificacion - Envio' WHERE accion = 'Bonificacion Envio';");
        
    }

    public function down()
    {

    }
}