<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version465 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('descuento', 'fecha_expiracion');
    }

    public function down()
    {
        $this->addColumn('descuento', 'fecha_expiracion', 'timestamp', '25', array(
             ));
    }
}