<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version467 extends Doctrine_Migration_Base
{
    public function up()
    {
        $publicacionesMl = publicacionMlTable::getInstance()->findAll();
        
        foreach ($publicacionesMl as $publicacionMl)
        {
            if ( $publicacionMl->estaVigente() ) {
                $publicacionMl->setStatusMl('active');
            } else if ( $publicacionMl->estaVigente() ) {
                $publicacionMl->setStatusMl('closed'); 
            } else {
                $publicacionMl->setStatusMl(null);
            }
            
            $publicacionMl->save();
        }
    }

    public function down()
    {
    }
}