<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version466 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('publicacion_ml', 'status_ml', 'char', '6', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('publicacion_ml', 'status_ml');
    }
}