<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version468 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pedido', 'tipo_documento', 'string', '5', array(
             ));
        $this->addColumn('pedido', 'documento', 'string', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('pedido', 'tipo_documento');
        $this->removeColumn('pedido', 'documento');
    }
}