<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version475 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('producto', 'producto_id_eshop_eshop_id_eshop', array(
             'name' => 'producto_id_eshop_eshop_id_eshop',
             'local' => 'id_eshop',
             'foreign' => 'id_eshop',
             'foreignTable' => 'eshop',
             ));
        $this->addIndex('producto', 'producto_id_eshop', array(
             'fields' => 
             array(
              0 => 'id_eshop',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('producto', 'producto_id_eshop_eshop_id_eshop');
        $this->removeIndex('producto', 'producto_id_eshop', array(
             'fields' => 
             array(
              0 => 'id_eshop',
             ),
             ));
    }
}