<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version476 extends Doctrine_Migration_Base
{
    public function up()
    {
    	$permiso = new sfGuardPermission();
    	$permiso->setName('eshops_eshops');
    	$permiso->setDescription('eShops / eShops');
    	$permiso->save();
    }

    public function down()
    {
    }
}