<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version506 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('devolucion', 'id_eshop', 'integer', '4', array(
             ));
        $this->addColumn('fallado', 'id_eshop', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('devolucion', 'id_eshop');
        $this->removeColumn('fallado', 'id_eshop');
    }
}