<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version503 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute("ALTER TABLE usuario DROP INDEX email , ADD UNIQUE INDEX email (email ASC, id_eshop ASC);");
        $q->execute("ALTER TABLE newsletter DROP INDEX unique_row_idx , ADD UNIQUE INDEX unique_row_idx (email ASC, sexo ASC, id_eshop ASC);");
        
        
        
        
        
    }

    public function down()
    {
    }
}