<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version504 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('descuento', 'id_eshop', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('descuento', 'id_eshop');
    }
}