<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version495 extends Doctrine_Migration_Base
{
    public function up()
    {
        $eshop = eshopTable::getInstance()->findOneByIdEshop(1);
        $eshop->setMercadoPagoClientId( '581728787689355' );
        $eshop->setMercadoPagoClientSecret( 'ee1l1exRVM1orQcfuCe475CV3bIqt2uP' );
        $eshop->setMercadoPagoAccId( '568992955' );
        $eshop->setMercadoPagoEnc( 'MiU0mWJ5rSZ0gT%2FjwDpRURNKlao%3D' );
        $eshop->setMercadoPagoToken( 'HhUrdIGnAimI%2B5FxMb6kCDFVkFc%3D' );
        $eshop->save();
        
    }

    public function down()
    {
    }
}