<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version516 extends Doctrine_Migration_Base
{
    public function up()
    {
        $permiso = sfGuardPermissionTable::getInstance()->findOneByName('gestion_bajas_por_fuera_de_plazo');
        $permiso->delete();
    }

    public function down()
    {
        
    }
}