<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version527 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'oca_operativa_dom_cliente', 'string', '5', array(
             'fixed' => '1',
             ));
        $this->addColumn('eshop', 'oca_operativa_oca_cliente', 'string', '5', array(
             'fixed' => '1',
             ));
        $this->addColumn('eshop', 'oca_operativa_dom_empresa', 'string', '5', array(
             'fixed' => '1',
             ));
        $this->addColumn('eshop', 'oca_operativa_oca_empresa', 'string', '5', array(
             'fixed' => '1',
             ));
        $this->addColumn('eshop', 'oca_operativa_inversa', 'string', '5', array(
             'fixed' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('eshop', 'oca_operativa_dom_cliente');
        $this->removeColumn('eshop', 'oca_operativa_oca_cliente');
        $this->removeColumn('eshop', 'oca_operativa_dom_empresa');
        $this->removeColumn('eshop', 'oca_operativa_oca_empresa');
        $this->removeColumn('eshop', 'oca_operativa_inversa');
    }
}