<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version528 extends Doctrine_Migration_Base
{
    public function up()
    {
        $eshop = eshopTable::getInstance()->findOneByIdEshop(1);
        $eshop->setOcaOperativaDOMCliente(null);
        $eshop->setOcaOperativaOCACliente(null);
        $eshop->setOcaOperativaDOMEmpresa('98706');
        $eshop->setOcaOperativaOCAEmpresa('98708');
        $eshop->setOcaOperativaInversa('98709');
        $eshop->save();
        
        $eshop = eshopTable::getInstance()->findOneByIdEshop(2);
        $eshop->setOcaOperativaDOMCliente(null);
        $eshop->setOcaOperativaOCACliente(null);
        $eshop->setOcaOperativaDOMEmpresa('98695');
        $eshop->setOcaOperativaOCAEmpresa('98696');
        $eshop->setOcaOperativaInversa('98702');
        $eshop->save();

        $eshop = eshopTable::getInstance()->findOneByIdEshop(3);
        $eshop->setOcaOperativaDOMCliente(null);
        $eshop->setOcaOperativaOCACliente(null);
        $eshop->setOcaOperativaDOMEmpresa('98710');
        $eshop->setOcaOperativaOCAEmpresa('98711');
        $eshop->setOcaOperativaInversa('98713');
        $eshop->save();
        
    }

    public function down()
    {
        
    }
}