<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version543 extends Doctrine_Migration_Base
{
    public function up()
    {
        $eshop = eshopTable::getInstance()->findOneByIdEshop(2);
        $tagCompra = <<<EOF
        
<!-- Facebook Conversion Code for Re ventas -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6019419971965', {'value':'0.01','currency':'ARS'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6019419971965&amp;cd[value]=0.01&amp;cd[currency]=ARS&amp;noscript=1" /></noscript>
        

EOF;
            
        $eshop->setTagsCompra($tagCompra);
        $eshop->save();
    }

    public function down()
    {
    }
}