<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version539 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('recupero_carrito', 'mail_enviado', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('recupero_carrito', 'mail_enviado');
    }
}