<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version558 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('eshop', 'ml_id_usuario_interno', 'integer', '4', array());
        $this->addColumn('eshop', 'ml_id_official_store', 'integer', '4', array());
        
    }

    public function down()
    {
        $this->removeColumn('eshop', 'ml_id_usuario_interno');
        $this->removeColumn('eshop', 'ml_id_official_store');
    }
}