<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version546 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('recibo_eshop', array(
             'id_recibo_eshop' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'tipo' => 
             array(
              'type' => 'char',
              'length' => '2',
             ),
             'importe' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '12',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id_recibo_eshop',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('recibo_eshop_pedido', array(
             'id_recibo_eshop' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'id_pedido' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'fk_reciboEshopPedido_id_recibo_eshop' => 
              array(
              'fields' => 
              array(
               0 => 'id_recibo_eshop',
              ),
              ),
              'fk_reciboEshopPedido_id_pedido' => 
              array(
              'fields' => 
              array(
               0 => 'id_pedido',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id_recibo_eshop',
              1 => 'id_pedido',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('recibo_eshop');
        $this->dropTable('recibo_eshop_pedido');
    }
}