<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version552 extends Doctrine_Migration_Base
{
    public function up()
    {
        $reporte = reporteCronologicoTable::getInstance()->createQuery('r')
                    ->addSelect('r.fecha, r.id_pedido, r.bonificacion_devolucion_mp, r.bonificacion_devolucion_deluxe, r.descuento, r.total_facturado, r.forma_pago, r.id_eshop')
                    ->addWhere('r.accion LIKE ?', "Bonificacion%" )
                    ->addWhere('r.id_eshop IS NOT NULL')
                    ->fetchArray();
        
        foreach ($reporte as $row) {
            $montoADevolver = $row['bonificacion_devolucion_mp'] + $row['bonificacion_devolucion_deluxe'];
            $reciboEshop = reciboEshopTable::getInstance()->insert( $row['id_eshop'], array( $row['id_pedido'] ), $montoADevolver, reciboEshop::TIPO_NOTA_DE_CREDITO );
                        
            $q = Doctrine_Manager::getInstance()->getCurrentConnection();
            $q->execute("UPDATE recibo_eshop set fecha = '" . $row['fecha'] . "' where id_recibo_eshop = " . $reciboEshop->getIdReciboEshop() . ";");
        }
        
        
        
    }

    public function down()
    {
        
    }
}