<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version556 extends Doctrine_Migration_Base
{
    public function up()
    {
        $eshop = eshopTable::getInstance()->findOneByIdEshop(4);
        $eshop->setLinkColor('#000000');
        $eshop->save();
        
    }

    public function down()
    {
        
    }
}