<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version575 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pedido', 'envio_id_locker_oca', 'integer', '4', array(
             ));
        $this->addColumn('pedido', 'envio_id_tamanio_locker_oca', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('pedido', 'envio_id_locker_oca');
        $this->removeColumn('pedido', 'envio_id_tamanio_locker_oca');
    }
}