<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version574 extends Doctrine_Migration_Base
{
    public function up()
    {
		$tamanioLockerOca = new tamanioLockerOca();
		$tamanioLockerOca->setDenominacion('Pequeño (13x31x52)');
		$tamanioLockerOca->setIdExterno('2');
		$tamanioLockerOca->save();

		$tamanioLockerOca = new tamanioLockerOca();
		$tamanioLockerOca->setDenominacion('Mediano (28x31x52)');
		$tamanioLockerOca->setIdExterno('3');
		$tamanioLockerOca->save();

		$tamanioLockerOca = new tamanioLockerOca();
		$tamanioLockerOca->setDenominacion('Grande (43x31x52)');
		$tamanioLockerOca->setIdExterno('15');
		$tamanioLockerOca->save();
    }

    public function down()
    {

    }
}