<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version570 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('carrito_envio', 'carrito_envio_id_locker_oca_locker_oca_id_locker_oca', array(
             'name' => 'carrito_envio_id_locker_oca_locker_oca_id_locker_oca',
             'local' => 'id_locker_oca',
             'foreign' => 'id_locker_oca',
             'foreignTable' => 'locker_oca',
             ));
        $this->addIndex('carrito_envio', 'carrito_envio_id_locker_oca', array(
             'fields' => 
             array(
              0 => 'id_locker_oca',
             ),
             ));
        $this->addIndex('carrito_envio', 'fk_carrito_envio_locker_oca1', array(
             'fields' => 
             array(
              0 => 'id_locker_oca',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('carrito_envio', 'carrito_envio_id_locker_oca_locker_oca_id_locker_oca');
        $this->removeIndex('carrito_envio', 'carrito_envio_id_locker_oca', array(
             'fields' => 
             array(
              0 => 'id_locker_oca',
             ),
             ));
        $this->removeIndex('carrito_envio', 'fk_carrito_envio_locker_oca1', array(
             'fields' => 
             array(
              0 => 'id_locker_oca',
             ),
             ));
    }
}